import fs from 'fs';

const glossary = [
  // Economics & Metrics
  {
    "term": "Customer Acquisition Cost (CAC)",
    "slug": "customer-acquisition-cost",
    "category": "Economics & Metrics",
    "definition": "The total cost to acquire a new paying customer, including all marketing and sales expenses, salaries, overhead, and ad spend over a specific period.",
    "why_it_matters": "CAC determines the fundamental scalability of your growth model. If it costs more to acquire a customer than they generate in profit, the business model is structurally flawed.",
    "example_in_practice": "If a company spends $10,000 on sales and marketing in a month and acquires 100 new customers, their CAC is $100. This must be compared against the customer's lifetime value.",
    "related_terms": ["LTV", "CAC Payback Period", "Blended CAC"],
    "formula": "CAC = Total Sales & Marketing Expenses / Number of New Customers Acquired"
  },
  {
    "term": "Lifetime Value (LTV)",
    "slug": "lifetime-value",
    "category": "Economics & Metrics",
    "definition": "The total gross profit a business expects to earn from a single customer throughout their entire relationship before they churn.",
    "why_it_matters": "LTV dictates how much you can afford to spend on acquiring a customer (CAC). High LTV businesses can outspend competitors on marketing and still remain profitable.",
    "example_in_practice": "A customer pays $100/month with an 80% gross margin. If the average customer stays for 24 months, their LTV is ($100 * 0.8) * 24 = $1,920.",
    "related_terms": ["CAC", "ARPU", "Churn Rate"],
    "formula": "LTV = (Average Revenue Per User × Gross Margin %) / Churn Rate"
  },
  {
    "term": "LTV:CAC Ratio",
    "slug": "ltv-cac-ratio",
    "category": "Economics & Metrics",
    "definition": "The relationship between the lifetime value of a customer and the cost to acquire them. It measures the ROI of sales and marketing efforts.",
    "why_it_matters": "A 3:1 ratio is generally considered the benchmark for a healthy SaaS business. Less than 1:1 means you lose money on every customer. Higher than 5:1 might mean you are under-investing in growth.",
    "example_in_practice": "If your LTV is $3,000 and your CAC is $1,000, your LTV:CAC ratio is 3:1.",
    "related_terms": ["LTV", "CAC", "Unit Economics"],
    "formula": "LTV:CAC Ratio = LTV / CAC"
  },
  {
    "term": "CAC Payback Period",
    "slug": "cac-payback-period",
    "category": "Economics & Metrics",
    "definition": "The number of months it takes for the gross margin generated by a customer to pay back the cost of acquiring that customer.",
    "why_it_matters": "Shorter payback periods mean less working capital is tied up in acquiring customers. Most startups aim for a payback period of 12 months or less.",
    "example_in_practice": "If CAC is $1,200 and a customer generates $100 in gross margin per month, it will take 12 months to break even on that acquisition.",
    "related_terms": ["CAC", "Gross Margin", "Cash Flow"],
    "formula": "Payback Period = CAC / (Monthly ARPU × Gross Margin %)"
  },
  {
    "term": "Average Revenue Per User (ARPU)",
    "slug": "average-revenue-per-user",
    "category": "Economics & Metrics",
    "definition": "The average amount of revenue generated by each active user or account over a specific time period, typically measured monthly or annually.",
    "why_it_matters": "ARPU is a core health metric. Increasing ARPU without increasing CAC significantly improves overall profitability and indicates customers derive increasing value.",
    "example_in_practice": "If a SaaS company has $100,000 in MRR and 500 active customers, their ARPU is $200 per month.",
    "related_terms": ["ACV", "MRR", "Expansion Revenue"],
    "formula": "ARPU = Total Revenue / Total Number of Active Users"
  },
  {
    "term": "Average Contract Value (ACV)",
    "slug": "average-contract-value",
    "category": "Economics & Metrics",
    "definition": "The average annualized revenue per customer contract. Excludes one-time fees like implementation or training.",
    "why_it_matters": "ACV helps dictate your sales motion. A low ACV requires high-volume, low-touch sales, while a high ACV can support enterprise, high-touch sales teams.",
    "example_in_practice": "A customer signs a 3-year deal for $30,000. The ACV is $10,000. If they also pay a $5,000 setup fee, the ACV remains $10,000.",
    "related_terms": ["TCV", "ARPU"],
    "formula": "ACV = Total Annualized Contract Revenue / Number of Contracts"
  },
  {
    "term": "Total Contract Value (TCV)",
    "slug": "total-contract-value",
    "category": "Economics & Metrics",
    "definition": "The total revenue expected from a contract across its entire duration, including one-time fees and professional services.",
    "why_it_matters": "TCV gives a holistic view of the revenue a deal brings in, which is crucial for calculating sales commissions and forecasting long-term cash flow.",
    "example_in_practice": "A 3-year software license at $10,000/year plus a $5,000 onboarding fee yields a TCV of $35,000.",
    "related_terms": ["ACV", "Bookings"]
  },
  {
    "term": "Gross Margin",
    "slug": "gross-margin",
    "category": "Economics & Metrics",
    "definition": "The percentage of revenue that remains after deducting the direct costs associated with delivering the product or service (Cost of Goods Sold).",
    "why_it_matters": "Software companies command high valuations precisely because they have high gross margins (typically 70-90%), meaning most new revenue drops straight to the bottom line.",
    "example_in_practice": "If you sell a software subscription for $100 and hosting/support costs $15, your gross margin is 85%.",
    "related_terms": ["COGS", "Net Margin", "EBITDA"],
    "formula": "Gross Margin = ((Revenue - COGS) / Revenue) × 100"
  },
  {
    "term": "Cost of Goods Sold (COGS)",
    "slug": "cogs",
    "category": "Economics & Metrics",
    "definition": "The direct costs attributable to the production or delivery of the goods or services sold by a company. For software, this includes hosting, third-party data APIs, and customer support.",
    "why_it_matters": "COGS is the foundational variable that determines gross margin. Startups must fiercely optimize COGS as they scale to maintain software-like margins.",
    "example_in_practice": "For a GenAI startup, the API costs paid to OpenAI or Anthropic for every user query represent the primary COGS.",
    "related_terms": ["Gross Margin", "Opex"]
  },
  {
    "term": "Unit Economics",
    "slug": "unit-economics",
    "category": "Economics & Metrics",
    "definition": "The direct revenues and costs associated with a single fundamental unit of a business model (usually one customer or one transaction).",
    "why_it_matters": "If unit economics are negative, scaling the business simply means losing money faster. Positive unit economics are the prerequisite for sustainable growth.",
    "example_in_practice": "An e-commerce company calculating the revenue of a single shirt sold minus the cost of the shirt, packaging, shipping, and the ad spend required to get the sale.",
    "related_terms": ["LTV", "CAC", "Gross Margin"]
  },

  // Market Sizing
  {
    "term": "Total Addressable Market (TAM)",
    "slug": "total-addressable-market",
    "category": "Market Sizing",
    "definition": "The total global or regional market demand for a product or service, calculated as the maximum possible annual revenue if the company captured 100% market share.",
    "why_it_matters": "Investors use TAM to gauge the absolute ceiling of a startup's potential. A venture-scale business typically requires a TAM in the billions.",
    "example_in_practice": "If there are 1 million independent restaurants in the world and your software costs $1,000 per year, your TAM is $1 Billion.",
    "related_terms": ["SAM", "SOM", "Bottom-Up Analysis"],
    "formula": "TAM = Total Target Accounts × Average Annual Contract Value (ACV)"
  },
  {
    "term": "Serviceable Addressable Market (SAM)",
    "slug": "serviceable-addressable-market",
    "category": "Market Sizing",
    "definition": "The specific segment of the Total Addressable Market that a company can realistically target and serve given its current geography, channel capabilities, and product specialization.",
    "why_it_matters": "SAM grounds the TAM in reality. It shows investors what portion of the market the startup's current product roadmap and go-to-market strategy can actually reach.",
    "example_in_practice": "While the TAM might be all global restaurants, if your software is only in English and requires a specific point-of-sale system, your SAM is only English-speaking restaurants using that POS.",
    "related_terms": ["TAM", "SOM"]
  },
  {
    "term": "Serviceable Obtainable Market (SOM)",
    "slug": "serviceable-obtainable-market",
    "category": "Market Sizing",
    "definition": "The realistic portion of the SAM that a company expects to capture within the next 12 to 36 months, factoring in competition and current sales resources.",
    "why_it_matters": "SOM represents the immediate revenue goal. It proves to investors that the founders have a pragmatic understanding of their near-term sales capacity.",
    "example_in_practice": "If your SAM is $100M, but you only have 2 sales reps who can close $1M each per year, your realistic SOM for the next year is $2M.",
    "related_terms": ["SAM", "Market Share"]
  },
  {
    "term": "Bottom-Up Market Sizing",
    "slug": "bottom-up-market-sizing",
    "category": "Market Sizing",
    "definition": "Calculating market size by multiplying the exact number of potential customers by the realistic price they would pay, rather than relying on top-level industry reports.",
    "why_it_matters": "Investors strongly prefer bottom-up sizing because it proves the founder understands the unit economics and the actual customer base, avoiding the 'we just need 1% of a $10B market' fallacy.",
    "example_in_practice": "Finding there are 50,000 dental clinics in the US, and estimating 20% would pay $500/month for scheduling software, yielding a $60M SAM.",
    "related_terms": ["Top-Down Market Sizing", "TAM"]
  },
  {
    "term": "Top-Down Market Sizing",
    "slug": "top-down-market-sizing",
    "category": "Market Sizing",
    "definition": "Calculating market size by starting with a broad industry macro-estimate from a research firm (like Gartner or Forrester) and filtering it down.",
    "why_it_matters": "While often used in early pitch decks, it is generally considered less rigorous than bottom-up sizing and often overstates realistic market potential.",
    "example_in_practice": "Stating 'The global AI market is $500B, and we are targeting the healthcare segment which is 10%, so our market is $50B.'",
    "related_terms": ["Bottom-Up Market Sizing", "TAM"]
  },

  // SaaS & Subscription
  {
    "term": "Monthly Recurring Revenue (MRR)",
    "slug": "monthly-recurring-revenue",
    "category": "SaaS & Subscription",
    "definition": "The normalized monthly amount of subscription revenue a company expects to receive. It excludes one-time fees.",
    "why_it_matters": "MRR is the lifeblood of a SaaS business. It provides predictability, allowing founders to forecast cash flow and invest in growth with confidence.",
    "example_in_practice": "If a customer signs a $12,000 annual contract, it contributes $1,000 to MRR.",
    "related_terms": ["ARR", "Churn", "Net Retention Rate"],
    "formula": "MRR = Total Active Subscriptions × Monthly Subscription Price"
  },
  {
    "term": "Annual Recurring Revenue (ARR)",
    "slug": "annual-recurring-revenue",
    "category": "SaaS & Subscription",
    "definition": "The annualized version of MRR. It represents the recurring revenue a company would generate over a year based on the current month's active subscriptions.",
    "why_it_matters": "ARR is the standard metric used for valuation in enterprise SaaS. Startups are often valued at a multiple of their ARR (e.g., 10x ARR).",
    "example_in_practice": "If your MRR is $50,000 in December, your ARR is $600,000.",
    "related_terms": ["MRR", "Valuation Multiple"],
    "formula": "ARR = MRR × 12"
  },
  {
    "term": "Customer Churn Rate",
    "slug": "customer-churn-rate",
    "category": "SaaS & Subscription",
    "definition": "The percentage of total customers who cancel their subscription over a given period.",
    "why_it_matters": "High churn is fatal to subscription businesses. If churn outpaces acquisition, growth stalls entirely. A good logo churn rate for SMB SaaS is <3% monthly, and <10% annually for enterprise.",
    "example_in_practice": "If you start the month with 100 customers and 5 cancel, your monthly customer churn rate is 5%.",
    "related_terms": ["Revenue Churn", "Retention Rate", "LTV"],
    "formula": "Churn Rate = (Customers lost during period / Total customers at start of period) × 100"
  },
  {
    "term": "Gross Revenue Churn",
    "slug": "gross-revenue-churn",
    "category": "SaaS & Subscription",
    "definition": "The percentage of recurring revenue lost due to cancellations and downgrades over a given period.",
    "why_it_matters": "Gross revenue churn shows the baseline revenue leakage before accounting for upsells. It indicates if the core product is losing value for existing users.",
    "example_in_practice": "If you had $100k MRR, and lost $5k to cancellations and $2k to downgrades, your gross revenue churn is 7%.",
    "related_terms": ["Net Revenue Retention", "Customer Churn Rate"]
  },
  {
    "term": "Net Revenue Retention (NRR)",
    "slug": "net-revenue-retention",
    "category": "SaaS & Subscription",
    "definition": "The percentage of recurring revenue retained from existing customers over a period, factoring in downgrades, cancellations, and expansion (upsells/cross-sells).",
    "why_it_matters": "NRR > 100% means the business can grow revenue even if it acquires zero new customers. Top-tier public SaaS companies often have NRR between 110% and 130%.",
    "example_in_practice": "Starting MRR: $100k. Lost MRR: $5k. Downgraded: $2k. Expansion (Upsell): $15k. Ending MRR from that cohort: $108k. NRR is 108%.",
    "related_terms": ["Gross Revenue Churn", "Expansion Revenue"],
    "formula": "NRR = ((Starting MRR - Churn - Downgrades + Expansion) / Starting MRR) × 100"
  },
  {
    "term": "Expansion Revenue",
    "slug": "expansion-revenue",
    "category": "SaaS & Subscription",
    "definition": "Additional recurring revenue generated from existing customers through upselling (higher tiers), cross-selling (new products), or seat expansions.",
    "why_it_matters": "Expansion revenue is much cheaper to acquire than new logo revenue (CAC is near zero). It is the primary driver of Net Revenue Retention > 100%.",
    "example_in_practice": "A customer paying $100/mo for 10 seats upgrades to 15 seats, paying $150/mo. The $50 difference is expansion revenue.",
    "related_terms": ["NRR", "Upselling"]
  },
  {
    "term": "Billings",
    "slug": "billings",
    "category": "SaaS & Subscription",
    "definition": "The actual invoice amounts billed to customers in a period. This includes recognized recurring revenue plus changes in deferred revenue.",
    "why_it_matters": "While MRR measures revenue linearly over time, billings measures actual cash movement. High billings (like upfront annual payments) improve cash flow drastically.",
    "example_in_practice": "A customer signs a $12,000 annual contract and pays upfront on Day 1. The MRR is $1,000, but the Billings for that month is $12,000.",
    "related_terms": ["Deferred Revenue", "Bookings", "Cash Flow"]
  },
  {
    "term": "Deferred Revenue",
    "slug": "deferred-revenue",
    "category": "SaaS & Subscription",
    "definition": "Money received from customers for services that have not yet been delivered or recognized as revenue.",
    "why_it_matters": "Deferred revenue is a liability on the balance sheet but represents positive cash flow. It's the hallmark of a healthy SaaS business with annual upfront payments.",
    "example_in_practice": "Receiving $12,000 upfront for an annual software subscription creates $12,000 in deferred revenue, which converts to recognized revenue at $1,000 per month.",
    "related_terms": ["Billings", "Recognized Revenue"]
  },
  {
    "term": "Bookings",
    "slug": "bookings",
    "category": "SaaS & Subscription",
    "definition": "The total value of all signed contracts in a given period, regardless of when the cash is collected or revenue is recognized.",
    "why_it_matters": "Bookings are the ultimate leading indicator of future revenue growth. It measures the pure success of the sales team.",
    "example_in_practice": "If a sales rep signs a 3-year deal worth $30,000 total, the Bookings amount for that month is $30,000.",
    "related_terms": ["TCV", "Billings"]
  },

  // Finance & Operations
  {
    "term": "Burn Rate",
    "slug": "burn-rate",
    "category": "Finance & Operations",
    "definition": "The rate at which a company is losing money. Gross burn is total monthly expenses; Net burn is total expenses minus total revenue.",
    "why_it_matters": "Burn rate dictates survival. Founders must constantly monitor net burn to calculate their remaining runway before they run out of cash.",
    "example_in_practice": "If a startup spends $100k a month and generates $20k in revenue, the Net Burn Rate is $80k per month.",
    "related_terms": ["Runway", "Cash Flow"],
    "formula": "Net Burn Rate = Cash Balance at Start of Month - Cash Balance at End of Month"
  },
  {
    "term": "Runway",
    "slug": "runway",
    "category": "Finance & Operations",
    "definition": "The amount of time a company has before it runs out of cash, assuming current burn rates.",
    "why_it_matters": "Runway is the ultimate countdown clock for a startup. Founders typically need to start fundraising when they have 6 to 9 months of runway left.",
    "example_in_practice": "If a startup has $1,000,000 in the bank and a net burn rate of $100,000 per month, they have 10 months of runway.",
    "related_terms": ["Burn Rate", "Fundraising"],
    "formula": "Runway (Months) = Total Cash Balance / Net Monthly Burn Rate"
  },
  {
    "term": "Gross Merchandise Value (GMV)",
    "slug": "gross-merchandise-value",
    "category": "Finance & Operations",
    "definition": "The total dollar value of merchandise sold over a given period through a customer-to-customer or e-commerce marketplace.",
    "why_it_matters": "GMV measures the scale and throughput of a marketplace, but it is NOT revenue. Revenue is only the take rate (commission) the marketplace keeps.",
    "example_in_practice": "If eBay facilitates the sale of a $100 item and takes a 10% fee, the GMV is $100, but eBay's revenue is only $10.",
    "related_terms": ["Take Rate", "Marketplace"]
  },
  {
    "term": "Take Rate",
    "slug": "take-rate",
    "category": "Finance & Operations",
    "definition": "The percentage of Gross Merchandise Value (GMV) that a marketplace or platform retains as its revenue.",
    "why_it_matters": "The take rate defines the monetization power of a marketplace. High take rates (20-30%) require deep value creation, while low take rates (1-5%) rely on massive transaction volume.",
    "example_in_practice": "Uber charges a rider $20, pays the driver $15, and keeps $5. Uber's take rate is 25%.",
    "related_terms": ["GMV", "Marketplace Revenue"],
    "formula": "Take Rate = Platform Revenue / Gross Merchandise Value"
  },
  {
    "term": "EBITDA",
    "slug": "ebitda",
    "category": "Finance & Operations",
    "definition": "Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash flow and core profitability.",
    "why_it_matters": "While early-stage startups rarely focus on EBITDA (as they are usually unprofitable), it is the primary valuation metric for mature, private-equity-backed software companies (Rule of 40).",
    "example_in_practice": "A mature SaaS company has $10M in revenue, $6M in operating expenses, and excludes $1M in software amortization, yielding an EBITDA of $4M.",
    "related_terms": ["Rule of 40", "Operating Income"]
  },
  {
    "term": "Working Capital",
    "slug": "working-capital",
    "category": "Finance & Operations",
    "definition": "The difference between a company's current assets (cash, accounts receivable) and current liabilities (accounts payable, short-term debt).",
    "why_it_matters": "Positive working capital is required to meet short-term obligations. Hardware and e-commerce companies often struggle with working capital due to inventory cycles.",
    "example_in_practice": "If a hardware startup has $500k in inventory but owes suppliers $600k in 30 days, they have a negative working capital issue.",
    "related_terms": ["Cash Flow", "Accounts Receivable"],
    "formula": "Working Capital = Current Assets - Current Liabilities"
  },
  {
    "term": "Rule of 40",
    "slug": "rule-of-40",
    "category": "Finance & Operations",
    "definition": "A benchmark stating that a mature software company's combined growth rate and profit margin should exceed 40%.",
    "why_it_matters": "It balances the trade-off between growth and profitability. You can burn cash if you are growing incredibly fast, or grow slowly if you are highly profitable.",
    "example_in_practice": "A SaaS company growing revenue at 30% year-over-year with a 15% EBITDA margin has a score of 45, passing the Rule of 40.",
    "related_terms": ["EBITDA", "Revenue Growth"]
  },

  // Fundraising & Equity
  {
    "term": "Pre-Money Valuation",
    "slug": "pre-money-valuation",
    "category": "Fundraising & Equity",
    "definition": "The valuation of a company prior to a new round of investment capital being injected.",
    "why_it_matters": "Pre-money valuation determines exactly how much equity founders give up for the investment. It is the core point of negotiation in a term sheet.",
    "example_in_practice": "An investor offers $2M on an $8M pre-money valuation. The post-money valuation becomes $10M, meaning the investor owns 20% ($2M / $10M).",
    "related_terms": ["Post-Money Valuation", "Dilution"]
  },
  {
    "term": "Post-Money Valuation",
    "slug": "post-money-valuation",
    "category": "Fundraising & Equity",
    "definition": "The valuation of a company immediately after a new round of investment capital is added to its balance sheet.",
    "why_it_matters": "Post-money valuation is what dictates the actual ownership percentages. Your ownership is calculated against the post-money, not the pre-money.",
    "example_in_practice": "If your pre-money is $10M and you raise $5M, your post-money is $15M.",
    "related_terms": ["Pre-Money Valuation", "Cap Table"],
    "formula": "Post-Money Valuation = Pre-Money Valuation + Investment Amount"
  },
  {
    "term": "Dilution",
    "slug": "dilution",
    "category": "Fundraising & Equity",
    "definition": "The decrease in existing shareholders' ownership percentage of a company as a result of the issuance of new shares.",
    "why_it_matters": "Every time a startup raises money, issues options, or issues warrants, the founders' slice of the pie gets smaller. Standard dilution per VC round is 15-25%.",
    "example_in_practice": "You own 100% of 1,000 shares. The company issues 250 new shares to an investor. There are now 1,250 shares. You now own 80% (1,000/1,250), suffering 20% dilution.",
    "related_terms": ["Cap Table", "Option Pool"]
  },
  {
    "term": "SAFE (Simple Agreement for Future Equity)",
    "slug": "safe",
    "category": "Fundraising & Equity",
    "definition": "An investment contract popularized by Y Combinator where an investor provides capital in exchange for the right to equity at a later pricing event, rather than pricing the equity today.",
    "why_it_matters": "SAFEs are the standard for early-stage fundraising because they are fast, cheap to execute (low legal fees), and avoid the difficult task of pricing a pre-revenue company.",
    "example_in_practice": "A founder raises $500k on a SAFE with an $8M valuation cap. The investor doesn't get shares immediately, but will convert at the $8M cap when the Series A happens.",
    "related_terms": ["Valuation Cap", "Convertible Note", "Discount Rate"]
  },
  {
    "term": "Valuation Cap",
    "slug": "valuation-cap",
    "category": "Fundraising & Equity",
    "definition": "The maximum effective valuation at which a SAFE or Convertible Note will convert into equity, protecting early investors if the company's value skyrockets before the next round.",
    "why_it_matters": "The cap ensures early investors get a better price per share than later investors to compensate for taking early risk.",
    "example_in_practice": "An investor holds a SAFE with a $10M cap. The startup raises a Series A at a $20M valuation. The early investor gets shares priced as if the valuation was only $10M, effectively getting them half-price.",
    "related_terms": ["SAFE", "Discount Rate"]
  },
  {
    "term": "Discount Rate (in Fundraising)",
    "slug": "discount-rate",
    "category": "Fundraising & Equity",
    "definition": "A provision in a SAFE or Convertible Note that allows early investors to convert their investment into equity at a reduced price (typically 20%) compared to the next funding round.",
    "why_it_matters": "It's an alternative to a Valuation Cap to reward early investors. If a note has both a cap and a discount, the investor converts at whichever gives them the lower price per share.",
    "example_in_practice": "A SAFE has a 20% discount. The Series A investors pay $1.00 per share. The SAFE investor converts their money into shares at $0.80 per share.",
    "related_terms": ["SAFE", "Valuation Cap"]
  },
  {
    "term": "Convertible Note",
    "slug": "convertible-note",
    "category": "Fundraising & Equity",
    "definition": "A form of short-term debt that converts into equity, typically in conjunction with a future financing round. Unlike a SAFE, it carries an interest rate and a maturity date.",
    "why_it_matters": "Prior to SAFEs, notes were the standard. They are still used when investors want the downside protection of debt (interest and repayment obligations) while waiting for an equity conversion.",
    "example_in_practice": "A startup raises a $1M convertible note with 5% interest. If it converts in a year, the investor gets equity worth $1.05M.",
    "related_terms": ["SAFE", "Maturity Date"]
  },
  {
    "term": "Pro Rata Rights",
    "slug": "pro-rata-rights",
    "category": "Fundraising & Equity",
    "definition": "The right (but not obligation) of an investor to participate in future funding rounds to maintain their current ownership percentage, preventing dilution.",
    "why_it_matters": "VCs rely heavily on pro rata rights. It allows them to double down on their winners. If they own 10% of a company, pro rata gives them the right to purchase 10% of the next round.",
    "example_in_practice": "An investor owns 10% of a startup. The startup raises a new $10M round. The investor exercises their pro rata right to invest $1M in this new round to avoid being diluted.",
    "related_terms": ["Dilution", "Term Sheet"]
  },
  {
    "term": "Liquidation Preference",
    "slug": "liquidation-preference",
    "category": "Fundraising & Equity",
    "definition": "A clause defining who gets paid first—and how much—if the company is sold, liquidated, or goes bankrupt. Usually expressed as a multiple (e.g., 1x).",
    "why_it_matters": "It protects downside for investors. A standard 1x non-participating preference means the investor gets their money back before founders get anything in a fire sale.",
    "example_in_practice": "A VC invests $5M with a 1x liquidation preference. The company is sold for $6M. The VC takes $5M off the top, leaving only $1M for the founders and employees.",
    "related_terms": ["Participating Preferred", "Term Sheet"]
  },
  {
    "term": "Participating Preferred Stock",
    "slug": "participating-preferred",
    "category": "Fundraising & Equity",
    "definition": "A dreaded equity structure (often called 'double dipping') where an investor first gets their investment back (liquidation preference), and then also shares in the remaining proceeds according to their ownership percentage.",
    "why_it_matters": "Founders must avoid this. It significantly reduces founder payouts in an exit. Standard venture deals use 'non-participating preferred'.",
    "example_in_practice": "VC invests $5M for 50% with participating preferred. Company sells for $15M. VC takes $5M back first. Then VC takes 50% of the remaining $10M ($5M). VC total: $10M. Founders: $5M.",
    "related_terms": ["Liquidation Preference"]
  },
  {
    "term": "Cap Table (Capitalization Table)",
    "slug": "cap-table",
    "category": "Fundraising & Equity",
    "definition": "A ledger tracking the equity capitalization of a company. It lists who owns what, including founders, investors, and the employee option pool.",
    "why_it_matters": "The cap table is the ultimate source of truth for ownership and payout scenarios. A 'messy' cap table (too much dead equity, complex preferences) can deter future investors.",
    "example_in_practice": "Using software like Carta to model how a $5M Series A will impact the founder's percentage on the cap table.",
    "related_terms": ["Dilution", "Option Pool"]
  },
  {
    "term": "Option Pool (ESOP)",
    "slug": "option-pool",
    "category": "Fundraising & Equity",
    "definition": "A block of equity (typically 10-20%) reserved for future employees, advisors, and consultants.",
    "why_it_matters": "Investors usually require the option pool to be expanded *pre-money* during a fundraise, meaning the founders take 100% of the dilution for the new employee pool.",
    "example_in_practice": "Before closing a Series A, the VC requires expanding the option pool to 15%. This comes entirely out of the founders' ownership percentage before the VC's capital is factored in.",
    "related_terms": ["Vesting", "Cap Table"]
  },
  {
    "term": "Vesting",
    "slug": "vesting",
    "category": "Fundraising & Equity",
    "definition": "The process by which an employee or founder earns the right to their equity over time, rather than receiving it all upfront.",
    "why_it_matters": "Vesting protects the company. If a co-founder leaves after 2 months, vesting ensures they don't walk away with half the company. Standard startup vesting is 4 years with a 1-year cliff.",
    "example_in_practice": "A developer is granted 10,000 options over 4 years. After year 1, 2,500 options vest. Then, roughly 208 options vest each month for the remaining 3 years.",
    "related_terms": ["Cliff", "Option Pool"]
  },
  {
    "term": "Vesting Cliff",
    "slug": "vesting-cliff",
    "category": "Fundraising & Equity",
    "definition": "A waiting period (usually one year) before any equity begins to vest. If an employee leaves before the cliff, they receive zero equity.",
    "why_it_matters": "The cliff prevents equity leakage to bad hires who wash out quickly, saving the company the administrative burden of recovering tiny equity fractions.",
    "example_in_practice": "An employee with a 1-year cliff leaves at month 11. They walk away with 0 shares. If they leave at month 13, they keep 25% of their total grant plus one month's worth.",
    "related_terms": ["Vesting"]
  },
  {
    "term": "Down Round",
    "slug": "down-round",
    "category": "Fundraising & Equity",
    "definition": "A funding round where the pre-money valuation is lower than the post-money valuation of the previous round.",
    "why_it_matters": "Down rounds cause massive dilution for founders and early employees, often triggering anti-dilution protections for previous investors. It heavily impacts company morale.",
    "example_in_practice": "A startup raised at a $50M valuation in 2021. In 2023, they run out of cash and are forced to raise at a $20M valuation to survive.",
    "related_terms": ["Anti-Dilution", "Pre-Money Valuation"]
  },
  {
    "term": "Anti-Dilution Provision",
    "slug": "anti-dilution-provision",
    "category": "Fundraising & Equity",
    "definition": "A clause that protects an investor's ownership percentage in the event of a down round by automatically adjusting the price at which they converted their preferred stock.",
    "why_it_matters": "Broad-based weighted average is standard. 'Full ratchet' anti-dilution is predatory and effectively wipes out founders during a down round.",
    "example_in_practice": "An early VC bought shares at $5. In a down round, new shares are sold at $2. Anti-dilution retroactively grants the early VC more shares to lower their average cost.",
    "related_terms": ["Down Round", "Term Sheet"]
  },

  // Product & Growth
  {
    "term": "Product-Market Fit (PMF)",
    "slug": "product-market-fit",
    "category": "Product & Growth",
    "definition": "The degree to which a product satisfies a strong market demand. Often characterized by high retention, organic word-of-mouth growth, and usage outpacing infrastructure.",
    "why_it_matters": "PMF is the holy grail. Before PMF, the only goal is achieving it. Scaling sales and marketing before achieving PMF leads to high churn and wasted capital.",
    "example_in_practice": "Marc Andreessen defines it as 'the customers are buying the product just as fast as you can make it.' A flat retention curve (users stay forever) is the mathematical proof.",
    "related_terms": ["Retention Rate", "Aha Moment"]
  },
  {
    "term": "Aha Moment",
    "slug": "aha-moment",
    "category": "Product & Growth",
    "definition": "The specific moment when a new user realizes the core value of your product. Getting users to this moment quickly correlates directly with long-term retention.",
    "why_it_matters": "Onboarding funnels should be optimized entirely around driving users to the Aha moment as fast as possible, removing all unnecessary friction.",
    "example_in_practice": "For Facebook, it was 'connecting with 7 friends in 10 days'. For Slack, it was 'team sending 2,000 messages'.",
    "related_terms": ["Activation Rate", "Time to Value"]
  },
  {
    "term": "Time to Value (TTV)",
    "slug": "time-to-value",
    "category": "Product & Growth",
    "definition": "The amount of time it takes a new customer to experience the Aha moment or see tangible ROI from your product.",
    "why_it_matters": "High TTV leads to onboarding churn. Product-led growth (PLG) companies aggressively engineer their apps to bring TTV down to minutes, not weeks.",
    "example_in_practice": "A complex ERP software might have a TTV of 6 months. A self-serve scheduling tool like Calendly has a TTV of 5 minutes.",
    "related_terms": ["Aha Moment", "Activation Rate"]
  },
  {
    "term": "Activation Rate",
    "slug": "activation-rate",
    "category": "Product & Growth",
    "definition": "The percentage of signed-up users who successfully complete a predefined set of key actions representing the core value (the Aha moment).",
    "why_it_matters": "A high sign-up rate means nothing if activation is low. Improving activation is usually the highest leverage growth activity a startup can do.",
    "example_in_practice": "If 1,000 users sign up for a CRM, but only 200 import a contact list (the activation metric), the activation rate is 20%.",
    "related_terms": ["Aha Moment", "Onboarding"]
  },
  {
    "term": "Daily Active Users (DAU)",
    "slug": "daily-active-users",
    "category": "Product & Growth",
    "definition": "The number of unique users who interact with the product in a single 24-hour period.",
    "why_it_matters": "DAU is the critical engagement metric for consumer social apps, gaming, and daily productivity tools (like Slack).",
    "example_in_practice": "An app has 10,000 total downloads, but only 500 users open it on a given Tuesday. The DAU is 500.",
    "related_terms": ["MAU", "DAU/MAU Ratio"]
  },
  {
    "term": "Monthly Active Users (MAU)",
    "slug": "monthly-active-users",
    "category": "Product & Growth",
    "definition": "The number of unique users who interact with the product at least once in a 30-day period.",
    "why_it_matters": "MAU is the standard metric for B2B tools or consumer tools that aren't used daily (like Airbnb or tax software).",
    "example_in_practice": "A user logs in on the 1st of the month, the 15th, and the 28th. They count as exactly 1 MAU.",
    "related_terms": ["DAU", "DAU/MAU Ratio"]
  },
  {
    "term": "DAU/MAU Ratio",
    "slug": "dau-mau-ratio",
    "category": "Product & Growth",
    "definition": "The ratio of daily active users to monthly active users. It measures 'stickiness'—how often users are engaging with the product.",
    "why_it_matters": "A DAU/MAU ratio over 20% is considered good, while over 50% is world-class (e.g., WhatsApp, Instagram). It proves the product is a daily habit.",
    "example_in_practice": "If an app has 1,000 DAU and 10,000 MAU, the ratio is 10%. This means the average user opens the app 3 days out of a month.",
    "formula": "DAU/MAU Ratio = (Daily Active Users / Monthly Active Users) * 100",
    "related_terms": ["DAU", "MAU"]
  },
  {
    "term": "K-Factor (Viral Coefficient)",
    "slug": "k-factor",
    "category": "Product & Growth",
    "definition": "A metric that measures the viral growth rate of an application, defined by how many new users each existing user successfully invites.",
    "why_it_matters": "If K > 1, the product is undergoing exponential viral growth. If K < 1, viral growth will eventually burn out without paid acquisition.",
    "example_in_practice": "If 10 users send out 50 invites total, and 15 new users sign up from those invites, the K-Factor is 1.5 (exponential growth).",
    "related_terms": ["Network Effects", "Viral Loop"],
    "formula": "K = Number of Invites Sent per User × Conversion Rate of Invites"
  },
  {
    "term": "Network Effects",
    "slug": "network-effects",
    "category": "Product & Growth",
    "definition": "A phenomenon where a product or service gains additional value as more people use it.",
    "why_it_matters": "Network effects build the strongest defensive moats in technology. It becomes nearly impossible for competitors to displace a platform with strong network effects.",
    "example_in_practice": "A telephone is useless if only one person has it. The value scales exponentially as more people get one. (e.g., Facebook, Uber, Airbnb).",
    "related_terms": ["K-Factor", "Marketplace"]
  },
  {
    "term": "Net Promoter Score (NPS)",
    "slug": "net-promoter-score",
    "category": "Product & Growth",
    "definition": "A market research metric based on a single survey question: 'On a scale of 0-10, how likely are you to recommend us to a friend?'",
    "why_it_matters": "NPS is a proxy for customer satisfaction and word-of-mouth growth. Scores above 50 are excellent. Above 70 is world-class.",
    "example_in_practice": "Promoters (score 9-10) minus Detractors (score 0-6). If 60% are promoters and 10% are detractors, the NPS is 50.",
    "related_terms": ["CSAT", "Churn"],
    "formula": "NPS = % Promoters - % Detractors"
  },
  {
    "term": "Cohort Analysis",
    "slug": "cohort-analysis",
    "category": "Product & Growth",
    "definition": "Analyzing user behavior by breaking them into groups (cohorts) based on a shared characteristic, typically the month they signed up.",
    "why_it_matters": "It is the only way to accurately measure retention over time. Looking at blended averages hides whether recent product updates are improving or hurting retention.",
    "example_in_practice": "Tracking the 'January Signups' cohort to see what percentage remain active after 3 months, compared to the 'February Signups' cohort.",
    "related_terms": ["Retention Rate", "Churn"]
  },

  // Added depth terms for Marketing & Sales
  {
    "term": "Ideal Customer Profile (ICP)",
    "slug": "ideal-customer-profile",
    "category": "Marketing & Sales",
    "definition": "A categorical description of the perfect company or user that would derive the most value from your product, representing the most efficient acquisition targets.",
    "why_it_matters": "Targeting outside the ICP increases CAC, drives up churn, and distracts the product team with edge-case feature requests.",
    "example_in_practice": "B2B SaaS ICP: 'B2B software companies in North America, with 50-200 employees, using Salesforce, and dealing with compliance issues.'",
    "related_terms": ["Buyer Persona", "SAM"]
  },
  {
    "term": "Lead Velocity Rate (LVR)",
    "slug": "lead-velocity-rate",
    "category": "Marketing & Sales",
    "definition": "The month-over-month growth percentage of qualified leads entering the sales pipeline.",
    "why_it_matters": "LVR is the most reliable leading indicator of future revenue growth, even more so than current revenue, which is a lagging indicator.",
    "example_in_practice": "If marketing generated 100 qualified leads last month and 120 this month, the LVR is 20%.",
    "formula": "LVR = ((Current Month Leads - Last Month Leads) / Last Month Leads) × 100",
    "related_terms": ["MQL", "SQL"]
  },
  {
    "term": "Marketing Qualified Lead (MQL)",
    "slug": "marketing-qualified-lead",
    "category": "Marketing & Sales",
    "definition": "A prospect whose engagement levels suggest they are more likely to become a customer than other leads, but who is not yet ready for a sales conversation.",
    "why_it_matters": "MQLs serve as a bridge between marketing top-of-funnel and sales, ensuring sales reps don't waste time on unqualified traffic.",
    "example_in_practice": "A user downloads a whitepaper and attends a webinar, pushing their lead score high enough to be classified as an MQL.",
    "related_terms": ["SQL", "Lead Scoring"]
  },
  {
    "term": "Sales Qualified Lead (SQL)",
    "slug": "sales-qualified-lead",
    "category": "Marketing & Sales",
    "definition": "A prospective customer that has been researched and vetted by both marketing and sales, indicating they are ready for a direct sales pitch or demo.",
    "why_it_matters": "SQLs are the primary metric for outbound sales effectiveness. A high MQL to SQL conversion rate means marketing and sales are perfectly aligned.",
    "example_in_practice": "An MQL is contacted by a SDR, who confirms they have budget, authority, and immediate need (BANT), officially upgrading them to an SQL.",
    "related_terms": ["MQL", "BANT"]
  }
];

// Replicate and generate variations to reach > 100 entries
const baseData = [...glossary];

// We need a total of at least 100 terms. We will generate highly detailed synthetic entries for advanced topics to reach 101 terms.
const expandedTopics = [
    ["Average Order Value (AOV)", "average-order-value", "Economics & Metrics", "The average dollar amount spent each time a customer places an order on a website or app.", "Vital for e-commerce. Increasing AOV directly scales revenue without increasing customer acquisition costs.", "Bundling products or offering 'free shipping over $50' are tactics to increase AOV.", "AOV = Total Revenue / Number of Orders"],
    ["Cost Per Acquisition (CPA)", "cost-per-acquisition", "Marketing & Sales", "The cost to acquire a non-customer action, such as a lead, sign-up, or registration, rather than a paying customer.", "Allows marketing to optimize ad spend higher up in the funnel before a sale is completed.", "If $1,000 in ad spend yields 50 email signups, the CPA is $20 per lead.", "CPA = Total Ad Spend / Number of Acquisitions"],
    ["Cost Per Click (CPC)", "cost-per-click", "Marketing & Sales", "The price an advertiser pays every time someone clicks on their digital ad.", "CPC dictates the efficiency of search and display advertising. High CPCs require high downstream conversion rates to remain profitable.", "Bidding on the keyword 'business insurance' might have a CPC of $45 due to high competition.", "CPC = Total Cost of Clicks / Total Number of Clicks"],
    ["Return on Ad Spend (ROAS)", "return-on-ad-spend", "Marketing & Sales", "The amount of revenue generated for every dollar spent on advertising.", "It directly measures the effectiveness of digital campaigns. A ROAS of less than 1 means you are losing money on ads.", "If you spend $1,000 on Facebook ads and sell $4,000 worth of products, your ROAS is 4x (or 400%).", "ROAS = Revenue from Ad Campaign / Cost of Ad Campaign"],
    ["Click-Through Rate (CTR)", "click-through-rate", "Marketing & Sales", "The percentage of people who click on a specific link out of the total users who view a page, email, or ad.", "CTR measures the immediate relevance and appeal of your creative and messaging.", "If an ad is shown 1,000 times (impressions) and gets 20 clicks, the CTR is 2%.", "CTR = (Total Clicks / Total Impressions) * 100"],
    ["Conversion Rate", "conversion-rate", "Product & Growth", "The percentage of users who take a desired action (e.g., making a purchase, filling out a form) out of the total visitors.", "Small increases in conversion rate dramatically reduce overall CAC and improve profitability.", "If a landing page gets 1,000 visitors and 50 sign up, the conversion rate is 5%.", "Conversion Rate = (Conversions / Total Visitors) * 100"],
    ["Bounce Rate", "bounce-rate", "Product & Growth", "The percentage of visitors to a website who navigate away from the site after viewing only one page.", "High bounce rates indicate a mismatch between user intent (what they clicked on) and the landing page experience.", "A blog post might naturally have a high bounce rate (users read and leave), but a checkout page should have a low one.", "Bounce Rate = Single Page Visits / Total Visits"],
    ["Gross Profit", "gross-profit", "Finance & Operations", "The profit a company makes after deducting the costs associated with making and selling its products.", "It demonstrates the fundamental viability of the product before operating expenses are factored in.", "If total sales are $100,000 and COGS is $20,000, the gross profit is $80,000.", "Gross Profit = Total Revenue - COGS"],
    ["Net Income", "net-income", "Finance & Operations", "The company's total profit after subtracting all expenses, including COGS, operating expenses, interest, and taxes.", "It is the ultimate bottom line of a business, proving it is a sustainable, self-funding entity.", "A startup with $1M in revenue and $1.2M in total expenses has a negative net income (a net loss) of -$200k.", "Net Income = Total Revenue - Total Expenses"],
    ["Operating Expenses (Opex)", "opex", "Finance & Operations", "The expenses a business incurs through its normal business operations, excluding COGS.", "Startups must control Opex (like office space and non-essential travel) to extend their runway.", "Salaries, rent, software subscriptions, and marketing spend are typical operating expenses.", ""],
    ["Capital Expenditures (Capex)", "capex", "Finance & Operations", "Funds used by a company to acquire, upgrade, and maintain physical assets such as property, plants, buildings, technology, or equipment.", "Software companies typically have very low Capex, making them highly capital efficient compared to manufacturing.", "Buying servers for a data center is Capex; renting AWS space is Opex.", ""],
    ["Pre-Seed Round", "pre-seed-round", "Fundraising & Equity", "The earliest stage of funding a new company comes across, usually to fund the creation of the minimum viable product (MVP).", "This is the highest risk capital, often sourced from the founders themselves, friends, family, or angel investors.", "Raising $250k on a SAFE to hire the first engineer and build a prototype.", ""],
    ["Seed Round", "seed-round", "Fundraising & Equity", "The first official equity funding stage, typically used to find product-market fit and build the initial team.", "Seed rounds have grown larger over time, often ranging from $1M to $3M, allowing startups to operate for 18-24 months.", "Raising $2M to hire a core engineering and sales team to launch the product to the public.", ""],
    ["Series A", "series-a", "Fundraising & Equity", "The first significant round of venture capital financing, generally raised after the startup has proven product-market fit and a scalable revenue model.", "Series A investors expect clear unit economics and a predictable go-to-market engine to pour fuel on the fire.", "Raising $10M at a $40M valuation to scale the sales team nationwide.", ""],
    ["Lead Investor", "lead-investor", "Fundraising & Equity", "The investor or VC firm that organizes a specific round of funding, negotiates the valuation and terms, and usually writes the largest check.", "Securing a lead investor is the hardest part of fundraising. Once a lead sets the terms, other 'follow-on' investors quickly fill the round.", "Sequoia Capital issues a term sheet for $5M, acting as the lead, while smaller angels put in the remaining $1M.", ""],
    ["Term Sheet", "term-sheet", "Fundraising & Equity", "A non-binding agreement setting forth the basic terms and conditions under which an investment will be made.", "It acts as a template to develop more detailed legal documents. The most critical items are valuation, investment amount, and control rights.", "A 2-page document outlining a $5M investment for 20% equity with standard 1x liquidation preferences.", ""],
    ["Board of Directors", "board-of-directors", "Fundraising & Equity", "A group of individuals elected to represent shareholders, mandate corporate governance, and hire/fire the CEO.", "VCs usually require a board seat as a condition of leading a Series A round, formally shifting control dynamics.", "A standard early board is 2 founders, 1 VC, and 1 mutually agreed independent member.", ""],
    ["Vesting Schedule", "vesting-schedule", "Fundraising & Equity", "A timeline detailing when employees or founders earn full ownership of their granted equity.", "Aligns long-term incentives. Standard tech vesting is a 4-year schedule with a 1-year cliff.", "If you leave after 2 years on a 4-year schedule, you only keep 50% of your shares.", ""],
    ["83(b) Election", "83b-election", "Fundraising & Equity", "A tax provision that allows founders to pay taxes on the total value of their restricted stock at the time of granting, rather than as it vests.", "Missing the 30-day deadline for an 83(b) election can result in devastating tax bills for founders if the company's valuation grows rapidly.", "Filing a letter with the IRS 5 days after incorporating to lock in a $0 tax basis.", ""],
    ["Drag-Along Rights", "drag-along-rights", "Fundraising & Equity", "A provision allowing majority shareholders to force minority shareholders to join in the sale of a company.", "Prevents a tiny minority shareholder from blocking an acquisition that the founders and VCs want to accept.", "If investors holding 60% of shares vote to sell the company, the remaining 40% are forced to sell on the same terms.", ""],
    ["Tag-Along Rights", "tag-along-rights", "Fundraising & Equity", "A provision protecting minority shareholders, allowing them to join in a sale initiated by majority shareholders on the same terms.", "Ensures that founders or VCs can't secretly sell their shares at a premium while leaving employees with illiquid stock.", "If a founder sells their shares to private equity, tag-along rights let early employees sell their shares proportionally.", ""],
    ["Right of First Refusal (ROFR)", "right-of-first-refusal", "Fundraising & Equity", "A contractual right giving a party (usually the company or lead investors) the opportunity to buy shares before they are sold to an outside third party.", "Prevents unwanted external parties (like competitors) from secretly buying equity from early employees.", "Before an employee sells shares on secondary markets, they must offer them to the company at the same price.", ""],
    ["Secondary Market", "secondary-market", "Fundraising & Equity", "The market where investors and employees buy and sell previously issued private startup shares, rather than buying directly from the company.", "Provides liquidity to early employees and founders without waiting for an IPO or acquisition.", "An early engineer sells 10% of their vested options to a late-stage VC fund to buy a house.", ""],
    ["Initial Public Offering (IPO)", "ipo", "Fundraising & Equity", "The process of offering shares of a private corporation to the public in a new stock issuance.", "The ultimate liquidity event for venture-backed startups, allowing access to massive public capital markets.", "Snowflake debuting on the NYSE, allowing anyone with a brokerage account to buy shares.", ""],
    ["Acqui-hire", "acqui-hire", "Fundraising & Equity", "When a company is acquired primarily for the talent of its team, rather than its product, user base, or revenue.", "Often an honorable exit for a failing startup, providing soft landings for the team and modest returns to investors.", "Google buys a struggling AI startup for $5M just to hire its 3 machine learning engineers.", ""],
    ["Minimum Viable Product (MVP)", "minimum-viable-product", "Product & Growth", "A version of a product with just enough features to be usable by early customers who can then provide feedback for future product development.", "Prevents founders from spending years building features in a vacuum that nobody actually wants.", "Zappos started by taking photos of shoes in local stores and only buying them when an online order came in.", ""],
    ["Pivot", "pivot", "Product & Growth", "A fundamental shift in a startup's business strategy, product direction, or target market after discovering the original hypothesis was incorrect.", "Pivoting requires intellectual honesty. Holding onto a failing vision kills startups.", "Slack pivoting from a failed video game (Glitch) into an enterprise communication tool.", ""],
    ["Freemium", "freemium", "Product & Growth", "A business model where the core product is free, but premium features, advanced tools, or removes limitations cost money.", "Drives massive top-of-funnel user growth by removing friction, acting as its own marketing engine.", "Spotify offering free ad-supported listening, but charging for offline, ad-free listening.", ""],
    ["Product-Led Growth (PLG)", "product-led-growth", "Product & Growth", "A go-to-market strategy that relies on using your product as the main vehicle to acquire, activate, and retain customers.", "Dramatically lowers CAC compared to sales-led growth, as users self-serve and invite colleagues.", "Zoom's viral 40-minute limit forcing hosts to upgrade or invite others.", ""],
    ["Sales-Led Growth (SLG)", "sales-led-growth", "Marketing & Sales", "A traditional growth model where the sales team is responsible for driving revenue through outbound prospecting, demos, and contract negotiation.", "Necessary for high-ACV, complex enterprise products where buyers need hand-holding and security reviews.", "Selling a $500,000 ERP system requires an SLG motion.", ""],
    ["Bottom-Up Sales", "bottom-up-sales", "Marketing & Sales", "A sales strategy where a product is adopted by individual contributors or small teams within a company before being expanded to an enterprise-wide contract.", "Bypasses the traditional, slow IT procurement process, allowing the product to act as a Trojan horse.", "Developers adopting AWS individually, expensing it, until the CIO is forced to sign a corporate contract.", ""],
    ["Top-Down Sales", "top-down-sales", "Marketing & Sales", "A traditional enterprise sales strategy targeting C-level executives and decision-makers to mandate software adoption across the organization.", "Required for top-down system replacements (like HRIS or massive CRM migrations).", "Selling Workday directly to the CHRO.", ""],
    ["BANT", "bant", "Marketing & Sales", "A sales qualification framework standing for Budget, Authority, Need, and Timeline.", "Helps Account Executives determine if a prospect is actually capable of buying, preventing wasted time on dead-end deals.", "Asking a prospect 'Do you have $10k allocated this quarter, and are you the final signer?'", ""],
    ["Account-Based Marketing (ABM)", "account-based-marketing", "Marketing & Sales", "A highly targeted marketing strategy where marketing and sales teams collaborate to create personalized campaigns for specific high-value accounts.", "Inverts the traditional funnel. Instead of casting a wide net, you treat individual target companies as markets of one.", "Creating a custom landing page, sending direct mail, and running targeted LinkedIn ads specifically for decision-makers at Target.", ""],
    ["Customer Success", "customer-success", "Marketing & Sales", "The proactive function of ensuring customers achieve their desired outcomes while using your product.", "Different from reactive customer support. Customer Success drives expansion revenue (upsells) and prevents churn.", "A Customer Success Manager doing quarterly business reviews with a client to ensure they are using new features.", ""],
    ["Net Promoter Score (NPS)", "nps", "Product & Growth", "A metric assessing customer loyalty based on the question: 'How likely are you to recommend us?'", "NPS is a proxy for word-of-mouth growth. A high NPS dramatically lowers CAC.", "Scoring 8-10 are promoters. 0-6 are detractors.", "NPS = % Promoters - % Detractors"],
    ["Customer Satisfaction (CSAT)", "csat", "Product & Growth", "A metric measuring customer satisfaction with a specific interaction, purchase, or support ticket.", "Provides immediate, transactional feedback compared to the broad relationship metric of NPS.", "A prompt asking 'How would you rate your support experience today?' after a ticket closes.", ""],
    ["Service Level Agreement (SLA)", "sla", "Finance & Operations", "A documented agreement between a service provider and a customer that identifies the services required and the expected level of service.", "Critical in enterprise SaaS. Breaching an SLA (like failing to maintain 99.9% uptime) usually results in financial penalties.", "A contract stipulating a 2-hour response time for critical support tickets.", ""],
    ["Uptime", "uptime", "Finance & Operations", "The percentage of time that a system or network is operational and available to users.", "A core metric for SaaS reliability. 99.9% ('three nines') allows 8.7 hours of downtime per year; 99.999% ('five nines') allows 5 minutes.", "Status pages display uptime to build trust with prospects.", ""],
    ["Total Cost of Ownership (TCO)", "tco", "Finance & Operations", "The purchase price of an asset plus the costs of operation, maintenance, and support over its lifespan.", "Used in enterprise sales to prove that a seemingly expensive SaaS product is cheaper than maintaining on-premise servers.", "A $100k SaaS tool has a lower TCO than a $20k legacy software that requires a $120k dedicated IT admin.", ""],
    ["Return on Investment (ROI)", "roi", "Finance & Operations", "A performance measure used to evaluate the efficiency of an investment or compare the efficiency of multiple investments.", "The holy grail of B2B marketing. If you can definitively prove positive ROI, selling becomes trivial.", "Investing $10,000 in software that saves 5 employees 10 hours a week yields a massive ROI.", "ROI = (Net Profit / Cost of Investment) * 100"],
    ["Bootstrapping", "bootstrapping", "Fundraising & Equity", "Building a company entirely from personal finances or operating revenue without raising outside venture capital.", "Bootstrapped founders retain 100% control and equity, but must grow slower based on actual cash flow.", "Mailchimp famously bootstrapped to billions in revenue before being acquired.", ""],
    ["Venture Capital (VC)", "venture-capital", "Fundraising & Equity", "Private equity provided to startups and early-stage companies that have high growth potential, in exchange for equity.", "VC is a high-risk, high-reward game based on power laws—one massive success pays for 99 failures.", "Andreessen Horowitz investing $5M in a seed stage AI company.", ""],
    ["Angel Investor", "angel-investor", "Fundraising & Equity", "A high-net-worth individual who provides financial backing for small startups or entrepreneurs, typically in exchange for ownership equity.", "Angels write smaller checks ($10k-$100k) very early on, often bringing valuable mentorship and networks.", "A former successful SaaS founder writing a $25,000 check into a new startup.", ""],
    ["Family Office", "family-office", "Fundraising & Equity", "Private wealth management advisory firms that serve ultra-high-net-worth investors.", "They are increasingly acting like venture funds, writing large checks without the strict timelines of institutional VC.", "A billionaire's family office investing $2M in a climate tech startup.", ""],
    ["Incubator", "incubator", "Fundraising & Equity", "An organization designed to help startups grow by providing workspace, mentorship, and resources, usually before they have a product.", "Focuses on the earliest stage of ideation and team building.", "Idealab helping founders brainstorm ideas and providing an office.", ""],
    ["Accelerator", "accelerator", "Fundraising & Equity", "A cohort-based program that includes mentorship and educational components and culminates in a public pitch event or demo day.", "Accelerators provide structured, high-pressure environments to rapidly scale an MVP.", "Y Combinator investing $500k for 7% and running a 3-month sprint.", ""],
    ["Due Diligence", "due-diligence", "Fundraising & Equity", "An investigation, audit, or review performed to confirm facts or details of a matter under consideration, typically before finalizing an investment.", "The process where VCs verify revenue numbers, review code, check reference calls, and analyze legal documents.", "A VC hiring a legal firm to ensure all employee IP assignments are correctly signed.", ""],
    ["Cap Table Management", "cap-table-management", "Fundraising & Equity", "The process of managing the capitalization table using software to ensure accuracy during fundraises, 409A valuations, and employee option grants.", "Errors in a spreadsheet cap table can lead to massive legal liabilities and incorrect payouts during an exit.", "Using Carta to issue digital option grants to new hires.", ""],
    ["409A Valuation", "409a-valuation", "Fundraising & Equity", "An independent appraisal of the fair market value (FMV) of a private company's common stock, required by the IRS.", "It sets the strike price for employee stock options. A low 409A is good for employees (cheaper options).", "Paying a firm $3k to determine the common stock is worth $1 per share, while preferred VC stock is $5.", ""],
    ["Strike Price", "strike-price", "Fundraising & Equity", "The fixed price at which the owner of an option can purchase the underlying security or commodity.", "Employees only make money if the company sells for a price per share higher than their strike price.", "An employee gets options with a strike price of $1. The company IPOs at $10. They make $9 per share.", ""],
    ["Phantom Equity", "phantom-equity", "Fundraising & Equity", "A compensation plan that gives employees the right to receive a cash payment at a future date tied to the market value of shares, without granting actual stock.", "Often used in LLCs or bootstrapped companies where founders want to share upside without giving away voting rights or messing up the cap table.", "An executive receives a phantom equity bonus of $50k when the company is acquired, treated as cash bonus.", ""],
    ["Profit Sharing", "profit-sharing", "Finance & Operations", "An incentivized compensation program that awards employees a percentage of the company's profits.", "Common in bootstrapped agencies and profitable SMBs, but rare in VC-backed startups (which have no profits).", "A profitable dev shop giving 10% of quarterly profits back to the team.", ""],
    ["Employee Stock Ownership Plan (ESOP)", "esop", "Fundraising & Equity", "An employee benefit plan that gives workers ownership interest in the company.", "Cultivates an ownership mentality and acts as a massive retention tool.", "Silicon Valley standard where early engineers might own 0.5% to 1% of the company.", ""],
    ["Liquidity Event", "liquidity-event", "Fundraising & Equity", "An event that allows founders and early investors to cash out some or all of their ownership shares.", "The moment when 'paper wealth' becomes actual cash in a bank account.", "An IPO, acquisition, or secondary tender offer.", ""],
    ["Earnout", "earnout", "Fundraising & Equity", "A provision in a startup acquisition where the sellers receive additional future payments based on the performance of the business post-sale.", "Mitigates risk for the buyer and incentivizes founders to stay and integrate the company successfully.", "Selling a company for $10M upfront, plus a $5M earnout if revenue hits targets over the next 2 years.", ""],
    ["Acquisition", "acquisition", "Fundraising & Equity", "When one company purchases most or all of another company's shares to gain control of that company.", "The most common successful exit for startups.", "Salesforce acquiring Slack for $27 Billion.", ""],
    ["Merger", "merger", "Fundraising & Equity", "The combining of two or more companies into a single new corporate entity.", "Usually involves stock swaps between companies of roughly equal size.", "A horizontal merger between two regional software competitors to dominate a national market.", ""],
    ["Strategic Investor", "strategic-investor", "Fundraising & Equity", "A corporate investor (like Google Ventures or Intel Capital) that invests for both financial return and strategic value to their core business.", "They can provide massive distribution channels, but might scare off other competitors from acquiring you.", "Salesforce Ventures investing in a startup to ensure integration with their ecosystem.", ""],
    ["Financial Investor", "financial-investor", "Fundraising & Equity", "A traditional VC firm focused purely on maximizing financial return on their investment.", "They are generally agnostic to specific corporate synergies and push for the highest possible exit value.", "A standard tier-1 VC like Benchmark or Sequoia.", ""],
    ["Lead Generation", "lead-generation", "Marketing & Sales", "The process of attracting and converting strangers into prospects who have indicated interest in your company's product.", "The top of the sales funnel. Without leads, AEs have no one to talk to.", "Running a LinkedIn ad offering a free ebook in exchange for an email address.", ""],
    ["Inbound Marketing", "inbound-marketing", "Marketing & Sales", "A methodology that attracts customers by creating valuable content and experiences tailored to them.", "Builds long-term, compounding organic traffic. Much cheaper CAC than outbound.", "Writing SEO-optimized blog posts, creating YouTube tutorials, and hosting webinars.", ""],
    ["Outbound Marketing", "outbound-marketing", "Marketing & Sales", "A traditional method where a company initiates the conversation and sends its message out to an audience.", "Fast to execute and targetable, but often has lower conversion rates and annoys prospects.", "Cold emailing, cold calling, and direct mail campaigns.", ""],
    ["Search Engine Optimization (SEO)", "seo", "Marketing & Sales", "The practice of increasing the quantity and quality of traffic to your website through organic search engine results.", "A critical inbound channel. High SEO ranking acts as a massive, free, perpetual lead generation engine.", "Optimizing a landing page for the keyword 'best CRM for small business'.", ""],
    ["Search Engine Marketing (SEM)", "sem", "Marketing & Sales", "The practice of marketing a business using paid advertisements that appear on search engine results pages.", "Allows startups to instantly buy their way to the top of Google, capturing high-intent traffic.", "Paying $10 per click on Google Ads for a targeted keyword.", ""],
    ["Pay-Per-Click (PPC)", "ppc", "Marketing & Sales", "An internet advertising model used to drive traffic to websites, in which an advertiser pays a publisher when the ad is clicked.", "The dominant model of digital advertising.", "Google Ads and Facebook Ads are primarily PPC networks.", ""],
    ["Content Marketing", "content-marketing", "Marketing & Sales", "A strategic marketing approach focused on creating and distributing valuable, relevant, and consistent content to attract a defined audience.", "Builds brand authority and fuels SEO.", "Hubspot building a massive library of marketing templates and guides.", ""],
    ["Affiliate Marketing", "affiliate-marketing", "Marketing & Sales", "An arrangement where an online retailer pays a commission to an external website for traffic or sales generated from its referrals.", "A performance-based channel that outsources marketing risk to third parties.", "Amazon paying a tech blogger 4% commission when a reader buys a recommended laptop.", ""],
    ["Influencer Marketing", "influencer-marketing", "Marketing & Sales", "A form of social media marketing involving endorsements and product placement from influencers.", "Highly effective for consumer brands (D2C) targeting Gen Z and Millennials.", "Paying a TikTok creator $5,000 to feature a new skincare product in a video.", ""],
    ["Viral Marketing", "viral-marketing", "Marketing & Sales", "A strategy that encourages individuals to pass on a marketing message to others, creating potential for exponential growth.", "Extremely difficult to engineer intentionally, but results in zero-CAC growth.", "Dropbox offering extra free storage space for referring friends.", ""],
    ["Growth Hacking", "growth-hacking", "Marketing & Sales", "A subfield of marketing focused on rapid experimentation across marketing channels and product development to identify the most efficient ways to grow a business.", "Prioritizes low-cost, innovative, tech-driven tactics over traditional ad spend.", "Airbnb reverse-engineering Craigslist to auto-post their listings.", ""],
    ["User Experience (UX)", "ux", "Product & Growth", "The overall experience of a person using a product, especially in terms of how easy or pleasing it is to use.", "Great UX reduces churn, lowers support costs, and acts as a competitive moat against legacy software.", "Designing a frictionless 1-click checkout flow.", ""],
    ["User Interface (UI)", "ui", "Product & Growth", "The specific visual elements (buttons, icons, screens) that a user interacts with to use a product.", "While UX is the structural flow, UI is the visual presentation.", "Choosing modern typography, accessible colors, and consistent padding.", ""],
    ["A/B Testing", "ab-testing", "Product & Growth", "A randomized experimentation process wherein two or more versions of a variable (web page, page element, etc.) are shown to different segments of website visitors.", "Removes guesswork from product and marketing decisions by letting data declare the winner.", "Testing a red 'Buy Now' button against a green 'Buy Now' button to see which yields higher conversions.", ""],
    ["Multivariate Testing", "multivariate-testing", "Product & Growth", "A technique for testing a hypothesis in which multiple variables are modified.", "More complex than A/B testing, it requires massive traffic to achieve statistical significance.", "Testing 3 different headlines and 3 different images simultaneously (9 variations).", ""],
    ["Customer Relationship Management (CRM)", "crm", "Marketing & Sales", "Software used to manage interactions with customers and potential customers.", "The central nervous system of any sales organization. Without a CRM, leads leak and sales data is lost.", "Using Salesforce or HubSpot to track the status of 500 ongoing deals.", ""],
    ["Enterprise Resource Planning (ERP)", "erp", "Finance & Operations", "Software that organizations use to manage day-to-day business activities such as accounting, procurement, project management, and manufacturing.", "The backbone of large enterprises, notoriously complex and expensive to implement.", "SAP or Oracle managing the global supply chain of a Fortune 500 company.", ""],
    ["Software as a Service (SaaS)", "saas", "SaaS & Subscription", "A software licensing and delivery model in which software is licensed on a subscription basis and is centrally hosted.", "The dominant business model of the 21st century due to recurring revenue and scalable cloud delivery.", "Salesforce, Google Workspace, Slack.", ""],
    ["Platform as a Service (PaaS)", "paas", "SaaS & Subscription", "A category of cloud computing services that provides a platform allowing customers to develop, run, and manage applications.", "Abstracts away server management so developers can focus on writing code.", "Heroku or Vercel.", ""],
    ["Infrastructure as a Service (IaaS)", "iaas", "SaaS & Subscription", "Online services that provide high-level APIs used to dereference various low-level details of underlying network infrastructure.", "The foundational layer of the cloud.", "Amazon Web Services (AWS) EC2 instances.", ""],
    ["Application Programming Interface (API)", "api", "Product & Growth", "A set of protocols that allows different software applications to communicate with each other.", "The connective tissue of the internet. APIs allow startups to build on top of existing platforms.", "Stripe's API allowing an e-commerce site to process credit cards.", ""],
    ["Software Development Kit (SDK)", "sdk", "Product & Growth", "A collection of software development tools in one installable package, used to build applications for a specific platform.", "Makes it drastically easier for third-party developers to integrate with your product.", "Facebook providing an iOS SDK to let apps easily add 'Login with Facebook'.", ""],
    ["Open Source Software (OSS)", "oss", "Product & Growth", "Software with source code that anyone can inspect, modify, and enhance.", "Many massive companies monetize open source by offering premium hosting, security, or enterprise features.", "Red Hat monetizing Linux, or Vercel monetizing Next.js.", ""],
    ["Minimum Marketable Product (MMP)", "minimum-marketable-product", "Product & Growth", "The version of the MVP that is polished enough that customers are actually willing to pay for it.", "Bridges the gap between a hacky prototype and a commercial offering.", "Adding billing integration and a polished UI to a command-line tool.", ""],
    ["Agile Development", "agile", "Product & Growth", "An iterative approach to software development that emphasizes flexibility, interactive phases, and rapid delivery.", "Allows startups to pivot quickly based on user feedback rather than locking into year-long 'waterfall' plans.", "Working in 2-week 'sprints' to ship small features constantly.", ""],
    ["Technical Debt", "technical-debt", "Product & Growth", "The implied cost of additional rework caused by choosing an easy (limited) solution now instead of using a better approach that would take longer.", "Startups inevitably accumulate technical debt to hit early deadlines, but it must eventually be paid down or development grinds to a halt.", "Hardcoding user IDs instead of building a proper database relationship to launch a week early.", ""],
    ["Continuous Integration/Continuous Deployment (CI/CD)", "ci-cd", "Product & Growth", "A method to frequently deliver apps to customers by introducing automation into the stages of app development.", "Allows modern SaaS companies to deploy new code 50 times a day without breaking the site.", "Using GitHub Actions to automatically test and deploy code to production when merged.", ""],
    ["Single Sign-On (SSO)", "sso", "Product & Growth", "An authentication scheme that allows a user to log in with a single ID and password to any of several related, yet independent, software systems.", "A critical feature for selling into enterprise companies. Usually gated behind the highest pricing tier.", "Using Okta or Azure AD to log into Slack, Zoom, and Salesforce simultaneously.", ""],
    ["Data Processing Agreement (DPA)", "dpa", "Finance & Operations", "A legally binding contract between a data controller and a data processor, required for GDPR compliance.", "Necessary for any B2B SaaS company storing European user data.", "Signing a DPA with AWS outlining how they protect your server data.", ""],
    ["General Data Protection Regulation (GDPR)", "gdpr", "Finance & Operations", "A regulation in EU law on data protection and privacy in the European Union and the European Economic Area.", "Violations carry massive fines. Has fundamentally shifted how startups handle cookies and user data.", "Adding a cookie consent banner and a 'delete my account' button to comply.", ""],
    ["Service Organization Control 2 (SOC 2)", "soc-2", "Finance & Operations", "An auditing procedure that ensures your service providers securely manage your data.", "The gold-standard security certification required to sell software to mid-market and enterprise companies in the US.", "Spending $50k on auditors and penetration tests to prove your AWS setup is secure.", ""],
    ["Total Value of Locked (TVL)", "tvl", "Finance & Operations", "A metric used in decentralized finance (DeFi) to measure the overall health of a protocol, representing the amount of assets currently staked.", "The crypto equivalent of Assets Under Management (AUM).", "A decentralized exchange boasting $1 Billion in TVL.", ""],
    ["Average Revenue Per Account (ARPA)", "arpa", "Economics & Metrics", "A profitability metric that assesses a company's revenue generation on a per-account basis. Synonymous with ARPU in B2B context.", "Tracks whether you are successfully moving upmarket (ARPA goes up).", "Total monthly recurring revenue divided by total active accounts.", "ARPA = MRR / Total Active Accounts"],
    ["Customer Retention Cost (CRC)", "customer-retention-cost", "Economics & Metrics", "The total expenses a company incurs to retain its existing customers, including customer success teams, loyalty programs, and engagement software.", "While everyone tracks CAC, CRC is often ignored. High CRC can destroy unit economics even if CAC is low.", "Allocating the salaries of the entire Customer Success department.", ""],
    ["Return on Investment (ROI)", "roi", "Economics & Metrics", "The ratio of net profit to the cost of the investment. A high ROI means the investment's gains compare favorably to its cost.", "Used universally to justify marketing spend, software purchases, or hiring.", "A $10,000 ad campaign that generates $50,000 in net profit has an ROI of 400%.", "ROI = (Net Profit / Cost of Investment) × 100"],
    ["Burn Multiple", "burn-multiple", "Finance & Operations", "A metric that evaluates a startup's capital efficiency by measuring how much cash it burns to generate each new dollar of ARR.", "A Burn Multiple under 1x is amazing; over 3x is highly inefficient. It's the ultimate measure of growth efficiency.", "If a startup burns $2M in a year but only adds $1M in net new ARR, the Burn Multiple is 2.0x.", "Burn Multiple = Net Burn / Net New ARR"],
    ["Magic Number", "magic-number", "Economics & Metrics", "A metric measuring sales efficiency. It calculates the revenue generated for every dollar spent on sales and marketing.", "A Magic Number > 0.75 means you should pour more money into sales and marketing.", "If you spent $1M on S&M last quarter and ARR grew by $1M, your Magic Number is 1.0.", "Magic Number = (Current Q ARR - Previous Q ARR) / Previous Q S&M Spend"]
];

let finalGlossary = [...baseData];
expandedTopics.forEach(topic => {
    finalGlossary.push({
        term: topic[0],
        slug: topic[1],
        category: topic[2],
        definition: topic[3],
        why_it_matters: topic[4],
        example_in_practice: topic[5],
        formula: topic[6] ? topic[6] : undefined
    });
});

// Write to JSON
const output = {
  version: "2.0.0",
  generated_at: new Date().toISOString(),
  terms_count: finalGlossary.length,
  data_level: "ACTUAL",
  glossary: finalGlossary.sort((a,b) => a.term.localeCompare(b.term))
};

fs.writeFileSync('data/glossary.json', JSON.stringify(output, null, 2));
console.log(`Generated ${finalGlossary.length} terms`);
