import { useId, useState, type ReactNode } from "react";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, Calculator as CalculatorIcon, Check, CheckCheck, ChevronDown, CircleHelp, Compass, FileText, FolderOpen, LockKeyhole, Mail, RotateCcw, Search, ShieldCheck, Sparkles, Sprout, Users, Wallet, X } from "lucide-react";
import { CALCULATORS, fieldGroups, readValues, type Calculator, type Reading } from "@/lib/calculators";
import { CATEGORIES } from "./catalog";
import "./secondary.css";

type Category = (typeof CATEGORIES)[number];

export function secondaryMeta(title: string, description: string) {
  return { meta: [{ title: `${title} | BBI` }, { name: "description", content: description }] };
}

function SecondaryHeader({ eyebrow, title, description, parent }: { eyebrow: string; title: string; description: string; parent?: { label: string; href: string } }) {
  return <header className="secondary-header">
    <nav className="secondary-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span>{parent && <><a href={parent.href}>{parent.label}</a><span aria-hidden="true">/</span></>}<span aria-current="page">{eyebrow}</span></nav>
    <p className="eyebrow"><span className="secondary-dot" />{eyebrow}</p>
    <h1 className="page-heading">{title}</h1>
    <p className="secondary-lead muted">{description}</p>
  </header>;
}

function DraftNote({ children = "Research copy is being prepared. This is a preview of the page structure." }: { children?: ReactNode }) {
  return <p className="secondary-draft"><FileText size={15} aria-hidden="true" /><span>{children}</span></p>;
}

function EmptyPanel({ title, children, icon = "folder" }: { title: string; children: ReactNode; icon?: "folder" | "search" | "article" }) {
  const Icon = icon === "search" ? Search : icon === "article" ? FileText : FolderOpen;
  return <div className="glass-panel secondary-empty"><span className="secondary-icon"><Icon size={25} aria-hidden="true" /></span><h2>{title}</h2><p className="muted">{children}</p></div>;
}

export function SecondaryNotFound({ title, href, label }: { title: string; href: string; label: string }) {
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Page unavailable" title={title} description="There is no published page at this address." /><a className="button button-primary" href={href}>{label}<ArrowRight size={17} aria-hidden="true" /></a></div>;
}

function CategoryArtwork({ category }: { category: Category }) {
  return <div className="secondary-category-art"><img src={category.image} alt={category.alt} loading="lazy" width="640" height="480" /></div>;
}

export function ListsHub() {
  const [query, setQuery] = useState("");
  const categories = CATEGORIES.filter((category) => category.category_name.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="bbi-page secondary-page">
    <SecondaryHeader eyebrow="The reading lists" title="A clearer place to start." description="Browse the library as a collection. Compare who pays, what it takes, and whether an idea belongs in your life." />
    <div className="secondary-hub-intro glass-panel"><div><span className="pill">Free to explore</span><h2>Different paths. The same honest research.</h2><p className="muted">Every collection leads back to the full blueprints, including the reasons to walk away.</p></div><div className="secondary-hub-stat"><strong>14</strong><span>researched categories</span></div></div>
    <label className="secondary-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Find a reading list</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a reading list…" type="search" /></label>
    {categories.length ? <div className="secondary-collection-grid">{categories.map((category) => <a className="glass-panel secondary-collection" href={`/list/${category.category_slug}`} key={category.category_slug}><CategoryArtwork category={category} /><div className="secondary-collection-body"><p className="secondary-meta">{category.group}</p><h2>{category.category_name}</h2><div className="secondary-card-footer"><span>Explore collection</span><ArrowUpRight size={20} aria-hidden="true" /></div></div></a>)}</div> : <EmptyPanel title="No collections match that search." icon="search">Try a different word, or <button className="text-link" onClick={() => setQuery("")}>clear your search</button>.</EmptyPanel>}
  </div>;
}

export type SecondaryListEntry = { title: string; slug: string; summary: string; target_customer: string; how_you_make_money: string; cons_json: string[]; verdict: string };

// PLACEHOLDER: list research arrives through entries. No invented idea titles or slugs.
export function ListDetail({ category, entries = [] }: { category: Category; entries?: SecondaryListEntry[] }) {
  return <div className="bbi-page secondary-page">
    <SecondaryHeader eyebrow="Reading list" title={category.category_name} description="A collection to compare slowly. Start with the customer, understand the money, and read the reasons this might not be for you." parent={{ label: "Reading lists", href: "/list" }} />
    <div className="secondary-article-layout"><article className="secondary-article"><div className="secondary-feature-image glass-panel"><CategoryArtwork category={category} /><span className="pill">Collection overview</span></div><section id="collection"><h2 className="section-heading">Inside this collection</h2>{/* PLACEHOLDER: category introduction and methodology. */}<p className="muted">The collection introduction will explain the common customer, working pattern, and tradeoffs behind these blueprints.</p></section>
      {entries.length ? entries.map((entry) => <section className="glass-panel secondary-list-entry" key={entry.slug}><h2>{entry.title}</h2><p>{entry.summary}</p><dl className="secondary-answer-list"><div><dt>Who pays you</dt><dd>{entry.target_customer}</dd></div><div><dt>How the money works</dt><dd>{entry.how_you_make_money}</dd></div><div><dt>What hurts in year one</dt><dd>{entry.cons_json.join(" ")}</dd></div><div><dt>Founder fit</dt><dd>{entry.verdict}</dd></div></dl><a className="text-link" href={`/idea/${entry.slug}`}>Read the full blueprint <ArrowRight size={16} aria-hidden="true" /></a></section>) : <div className="glass-panel secondary-list-entry"><DraftNote /><h2>Blueprint entries</h2>{/* PLACEHOLDER: title, summary, target_customer, how_you_make_money, cons_json, verdict. */}<dl className="secondary-answer-list"><div><dt>Who pays you</dt><dd>Customer research will appear here.</dd></div><div><dt>How the money works</dt><dd>Revenue mechanics will appear here.</dd></div><div><dt>What hurts in year one</dt><dd>Researched risks will appear here.</dd></div><div><dt>Founder fit</dt><dd>The verdict will appear here, including when to walk away.</dd></div></dl></div>}
    </article><aside className="secondary-aside"><div className="glass-panel secondary-aside-card"><span className="secondary-icon"><BookOpen size={24} aria-hidden="true" /></span><h2>A list is just the beginning.</h2><p className="muted">The full blueprint is where the tradeoffs live.</p><a className="button button-primary" href={`/category/${category.category_slug}`}>Open this category<ArrowRight size={16} aria-hidden="true" /></a></div><div className="secondary-dark-card"><ShieldCheck size={26} aria-hidden="true" /><h2>Permission to pass.</h2><p>A “do not build this” verdict belongs beside every promising opportunity.</p></div></aside></div>
    <RelatedCollections current={category.category_slug} />
  </div>;
}

function RelatedCollections({ current }: { current: string }) {
  return <section className="secondary-section"><div className="secondary-section-heading"><h2 className="section-heading">Keep exploring</h2><a className="text-link" href="/list">All collections <ArrowUpRight size={16} aria-hidden="true" /></a></div><div className="secondary-related">{CATEGORIES.filter((category) => category.category_slug !== current).slice(0, 3).map((category) => <a href={`/list/${category.category_slug}`} className="glass-panel secondary-related-card" key={category.category_slug}><span>{category.category_name}</span><ArrowRight size={18} aria-hidden="true" /></a>)}</div></section>;
}

export function ToolsHub() {
  const icons = [CalculatorIcon, Sprout, Wallet, Compass];
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="The workbench" title="Put your numbers to work." description="Small, transparent calculators for the questions behind a business. Bring your own figures. See exactly how the answer is worked out." />
    <div className="secondary-tool-grid">{CALCULATORS.map((calculator, index) => { const Icon = icons[index] ?? CalculatorIcon; return <a className="glass-panel secondary-tool-card" href={`/calculator/${calculator.slug}`} key={calculator.slug}><div className="secondary-tool-top"><span className="secondary-icon"><Icon size={26} aria-hidden="true" /></span><span className="secondary-meta">Browser calculator</span></div><h2>{calculator.title} <span>{calculator.highlight}</span></h2><p className="muted">{calculator.answers}</p><div className="secondary-card-footer"><span>Open calculator</span><ArrowUpRight size={21} aria-hidden="true" /></div></a>; })}</div>
    <div className="secondary-inline-note"><ShieldCheck size={24} aria-hidden="true" /><div><h2>Your figures stay with you.</h2><p className="muted">These tools calculate locally. Inputs begin empty and are not saved or sent anywhere.</p></div></div>
  </div>;
}

function emptyCalculatorInputs(calculator: Calculator): Record<string, string> {
  return Object.fromEntries(calculator.fields.map((field) => [field.key, ""]));
}

export function CalculatorPage({ calculator }: { calculator: Calculator }) {
  const [typed, setTyped] = useState<Record<string, string>>(() => emptyCalculatorInputs(calculator));
  const [touched, setTouched] = useState<Record<string, boolean>>({});
  const inputPrefix = useId();
  const { values, issues } = readValues(calculator.fields, typed);
  const readings = issues.length === 0 ? calculator.compute(values) : [];
  const started = Object.values(typed).some((value) => value.trim().length > 0);
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Calculator" title={`${calculator.title} ${calculator.highlight}`} description={calculator.intro} parent={{ label: "The workbench", href: "/calculator" }} />
    <div className="secondary-calculator-layout"><form className="glass-panel secondary-form" onSubmit={(event) => event.preventDefault()}><div className="secondary-section-heading"><h2>Your numbers</h2><button type="button" className="text-link" onClick={() => { setTyped(emptyCalculatorInputs(calculator)); setTouched({}); }}><RotateCcw size={15} aria-hidden="true" />Reset</button></div><p className="muted">Enter your own figures. Your results update as you type.</p>
      {fieldGroups(calculator).map(({ group, fields }) => <fieldset className="secondary-fieldset" key={group}><legend className="secondary-meta">{group}</legend><div className="secondary-fields">{fields.map((field) => { const id = `${inputPrefix}-${field.key}`; const issue = touched[field.key] ? issues.find((item) => item.key === field.key) : undefined; return <div className="secondary-field" key={field.key}><label className="field-label" htmlFor={id}>{field.label} <span className="muted">({field.unitLabel})</span></label><div className="secondary-number-input">{field.prefix && <span aria-hidden="true">{field.prefix}</span>}<input id={id} name={field.key} type="text" inputMode="decimal" autoComplete="off" value={typed[field.key] ?? ""} onChange={(event) => setTyped((previous) => ({ ...previous, [field.key]: event.target.value }))} onBlur={() => setTouched((previous) => ({ ...previous, [field.key]: true }))} aria-invalid={Boolean(issue)} aria-describedby={`${id}-help${issue ? ` ${id}-error` : ""}`} />{field.suffix && <span className="secondary-unit" aria-hidden="true">{field.suffix}</span>}</div><p id={`${id}-help`} className="secondary-field-help">{field.help}</p>{issue && <p id={`${id}-error`} className="secondary-field-error">{issue.message}</p>}</div>; })}</div></fieldset>)}
    </form><aside className="secondary-calculator-result glass-panel" aria-live="polite" aria-atomic="true"><div className="secondary-result-label"><Sparkles size={18} aria-hidden="true" /><span className="secondary-meta">The result</span></div>{issues.length > 0 ? <><div className="secondary-result-empty" aria-hidden="true">—</div><h2>{started ? "A few details to finish." : "Ready when you are."}</h2><p className="muted">{started ? "Complete every field with a valid number to see your calculation." : "Add your figures and your answer will appear here, with the formula underneath."}</p></> : <ul className="secondary-readings">{readings.map((reading) => <CalculatorReading reading={reading} key={reading.key} />)}</ul>}<div className="secondary-result-footnote"><ShieldCheck size={15} aria-hidden="true" /><p>Arithmetic from your inputs. No forecasts or market assumptions.</p></div></aside></div>
    <section className="secondary-section"><h2 className="section-heading">Keep working it through</h2><div className="secondary-related">{CALCULATORS.filter((item) => item.slug !== calculator.slug).map((other) => <a className="glass-panel secondary-related-card" key={other.slug} href={`/calculator/${other.slug}`}><span>{other.title} {other.highlight}</span><ArrowRight size={18} aria-hidden="true" /></a>)}</div></section>
  </div>;
}

function CalculatorReading({ reading }: { reading: Reading }) {
  return <li><p className="secondary-meta">{reading.label}</p><strong className={`${reading.primary ? "secondary-primary-reading" : "secondary-reading"}${reading.status === "blocked" ? " secondary-reading-blocked" : ""}`}>{reading.display}</strong><p className="secondary-formula">{reading.formula}</p>{reading.note && <p className="secondary-field-help">{reading.note}</p>}</li>;
}

const validationPrompts = [
  { key: "customer", icon: Users, title: "Who specifically pays?", prompt: "Name the customer and the problem they already spend time or money on." },
  { key: "money", icon: Wallet, title: "How does the money work?", prompt: "Write down what you sell, how you charge, and the cost of delivering it." },
  { key: "risk", icon: ShieldCheck, title: "What will hurt in year one?", prompt: "What could stop you from getting customers or delivering consistently?" },
  { key: "fit", icon: Compass, title: "Does it fit your life?", prompt: "Describe the time, skills, and resources you can actually commit." },
];

export function ValidationPage({ category }: { category: Category }) {
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [reviewing, setReviewing] = useState(false);
  const prefix = useId();
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Before you begin" title={`Think it through: ${category.category_name}`} description="Use the research to ask better questions before you commit. This worksheet helps you collect your thoughts; it does not generate a verdict." parent={{ label: "Browse", href: "/browse" }} />
    <div className="secondary-article-layout"><div><form className="secondary-validation-form" onSubmit={(event) => { event.preventDefault(); setReviewing(true); }}>{validationPrompts.map((item) => <div className="glass-panel secondary-question-card" key={item.key}><span className="secondary-icon"><item.icon size={22} aria-hidden="true" /></span><label htmlFor={`${prefix}-${item.key}`}>{item.title}</label><p className="muted" id={`${prefix}-${item.key}-help`}>{item.prompt}</p><textarea className="input" id={`${prefix}-${item.key}`} aria-describedby={`${prefix}-${item.key}-help`} rows={3} value={notes[item.key] ?? ""} onChange={(event) => { setNotes((previous) => ({ ...previous, [item.key]: event.target.value })); setReviewing(false); }} placeholder="Your notes…" /></div>)}<div className="secondary-action-row"><button className="button button-primary" type="submit">Review my notes<ArrowRight size={17} aria-hidden="true" /></button><button className="text-link" type="button" onClick={() => { setNotes({}); setReviewing(false); }}>Clear notes</button></div></form>
      {reviewing && <section className="glass-panel secondary-notes-review" aria-live="polite"><h2>Your working notes</h2>{validationPrompts.map((item) => <div key={item.key}><h3>{item.title}</h3><p>{notes[item.key]?.trim() || "No notes added yet."}</p></div>)}<p className="muted">These notes are only on this page. Compare them with the researched blueprint before making your decision.</p></section>}
    </div><aside className="secondary-aside"><div className="glass-panel secondary-aside-card"><CategoryArtwork category={category} /><h2>Start with the research.</h2><p className="muted">Explore the customer, economics, risks, and founder-fit verdict for this category.</p><a className="button button-primary" href={`/category/${category.category_slug}`}>Browse blueprints<ArrowRight size={16} aria-hidden="true" /></a></div><div className="secondary-inline-note secondary-small-note"><LockKeyhole size={20} aria-hidden="true" /><p>Notes stay on this page and disappear when you leave or refresh.</p></div></aside></div>
  </div>;
}

export type SecondaryFaq = { question: string; answer: string };
const libraryFaqs: SecondaryFaq[] = [
  { question: "Is the whole library free?", answer: "Yes. All 290 researched blueprints are free to read, with no signup, paywall, or email gate." },
  { question: "What is inside a blueprint?", answer: "Who will pay you, how the money works, what will hurt in year one, and a straight founder-fit verdict." },
  { question: "Will BBI tell me not to build an idea?", answer: "Yes. A verdict can tell you an idea does not fit. Reasons to walk away belong beside reasons to begin." },
];

function FaqAccordion({ entries }: { entries: SecondaryFaq[] }) {
  return <div className="secondary-faq-list">{entries.map((entry) => <details className="glass-panel secondary-faq" key={entry.question}><summary>{entry.question}<ChevronDown size={18} aria-hidden="true" /></summary><div><p>{entry.answer}</p></div></details>)}</div>;
}

export function FaqHub() {
  const [query, setQuery] = useState("");
  const normalized = query.toLowerCase().trim();
  const entries = libraryFaqs.filter((faq) => `${faq.question} ${faq.answer}`.toLowerCase().includes(normalized));
  const categories = CATEGORIES.filter((category) => category.category_name.toLowerCase().includes(normalized));
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Questions, answered" title="Start with a little clarity." description="The practical questions about BBI, followed by a place for the research questions in each category." /><label className="secondary-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Search questions and categories</span><input type="search" placeholder="Search questions or categories…" value={query} onChange={(event) => setQuery(event.target.value)} /></label>
    {entries.length > 0 && <section className="secondary-section"><h2 className="section-heading">About the library</h2><FaqAccordion entries={entries} /></section>}
    {categories.length > 0 && <section className="secondary-section"><h2 className="section-heading">Explore by category</h2><div className="secondary-faq-categories">{categories.map((category) => <a className="glass-panel secondary-faq-category" key={category.category_slug} href={`/faq/${category.category_slug}`}><CircleHelp size={22} aria-hidden="true" /><span>{category.category_name}<small>Category questions</small></span><ArrowUpRight size={18} aria-hidden="true" /></a>)}</div></section>}
    {!entries.length && !categories.length && <EmptyPanel title="No matching questions yet." icon="search">Try another search, or <button className="text-link" onClick={() => setQuery("")}>see every category</button>.</EmptyPanel>}
    <div className="secondary-inline-note"><Mail size={23} aria-hidden="true" /><div><h2>Something else on your mind?</h2><a className="text-link" href="/contact">Visit the contact page <ArrowUpRight size={16} aria-hidden="true" /></a></div></div>
  </div>;
}

// PLACEHOLDER: category-specific researched questions and answers arrive through entries.
export function FaqCategory({ category, entries = [] }: { category: Category; entries?: SecondaryFaq[] }) {
  const [query, setQuery] = useState("");
  const filtered = entries.filter((entry) => `${entry.question} ${entry.answer}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Category questions" title={category.category_name} description="A home for practical answers about the customer, money, risks, and founder fit in this category." parent={{ label: "Questions", href: "/faq" }} /><div className="secondary-article-layout"><div><label className="secondary-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Search this category's questions</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a question…" /></label>{filtered.length ? <FaqAccordion entries={filtered} /> : entries.length ? <EmptyPanel title="No matching questions." icon="search">Try another word, or <button className="text-link" onClick={() => setQuery("")}>clear your search</button>.</EmptyPanel> : <><DraftNote /><EmptyPanel title="Category answers are being prepared." icon="article">The researched questions and answers will appear here.</EmptyPanel><section className="secondary-section"><h2 className="section-heading">Questions about BBI</h2><FaqAccordion entries={libraryFaqs} /></section></>}</div><aside className="glass-panel secondary-aside-card"><CategoryArtwork category={category} /><h2>Explore the category.</h2><p className="muted">Open the blueprint collection while these answers take shape.</p><a href={`/category/${category.category_slug}`} className="button button-primary">Browse category<ArrowRight size={16} aria-hidden="true" /></a></aside></div></div>;
}

export type SecondaryArticle = { title: string; slug: string; excerpt: string; author: string; date: string; sections: { heading: string; body: string }[] };

// PLACEHOLDER: replace this draft with an editorial record passed as props.
const draftArticle: SecondaryArticle = { title: "Article title", slug: "", excerpt: "The article introduction will frame a founder question and explain what the research covers.", author: "Author to be added", date: "Publication date to be added", sections: [ { heading: "The question", body: "The opening research context will appear here." }, { heading: "What the research says", body: "The evidence, sources, and practical implications will appear here." }, { heading: "What this means for you", body: "The founder takeaway and reasons to reconsider will appear here." } ] };

// PLACEHOLDER: published articles arrive through posts; the preview is explicitly an editorial draft.
export function BlogHub({ posts = [] }: { posts?: SecondaryArticle[] }) {
  const [query, setQuery] = useState("");
  const [showPreview, setShowPreview] = useState(false);
  const filtered = posts.filter((post) => `${post.title} ${post.excerpt}`.toLowerCase().includes(query.toLowerCase().trim()));
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Field notes" title="Think before you leap." description="A place for deeper reading on customers, economics, and the work of starting something." /><label className="secondary-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Search field notes</span><input type="search" placeholder="Search field notes…" value={query} onChange={(event) => setQuery(event.target.value)} /></label>{filtered.length ? <div className="secondary-editorial-grid">{filtered.map((post) => <a className="glass-panel secondary-editorial-card" key={post.slug} href={`/blog/${post.slug}`}><div className="secondary-editorial-art"><BookOpen size={42} aria-hidden="true" /></div><div><p className="secondary-meta">{post.date}</p><h2>{post.title}</h2><p className="muted">{post.excerpt}</p><span className="text-link">Read article <ArrowUpRight size={16} aria-hidden="true" /></span></div></a>)}</div> : posts.length ? <EmptyPanel title="No articles match that search." icon="search">Try another word or <button className="text-link" onClick={() => setQuery("")}>clear your search</button>.</EmptyPanel> : <div className="glass-panel secondary-editorial-placeholder"><div className="secondary-editorial-art"><BookOpen size={48} aria-hidden="true" /></div><div><DraftNote>Editorial draft · Research articles will appear here.</DraftNote><h2>Room for a deeper read.</h2><p className="muted">The library is where to explore business ideas. Field notes will be the place to spend more time with a question.</p><button className="button button-secondary" aria-expanded={showPreview} aria-controls="article-template-preview" onClick={() => setShowPreview((value) => !value)}>{showPreview ? "Close article preview" : "Preview article layout"}{showPreview ? <X size={17} aria-hidden="true" /> : <ArrowDown size={17} aria-hidden="true" />}</button></div></div>}{showPreview && <div id="article-template-preview" className="secondary-inline-article"><ArticleBody article={draftArticle} draft /></div>}</div>;
}

export function BlogArticlePage({ article = draftArticle }: { article?: SecondaryArticle }) {
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Field notes" title={article.title} description={article.excerpt} parent={{ label: "Field notes", href: "/blog" }} /><ArticleBody article={article} draft={!article.slug} /></div>;
}

function ArticleBody({ article, draft }: { article: SecondaryArticle; draft: boolean }) {
  return <><div className="secondary-article-byline"><span>{article.author}</span><span>{article.date}</span>{draft && <span className="pill">Draft preview</span>}</div><div className="secondary-article-layout"><article className="secondary-article"><div className="secondary-article-cover"><BookOpen size={58} aria-hidden="true" /><span>BBI / Field notes</span></div>{draft && <DraftNote>Draft template · This is placeholder editorial content.</DraftNote>}{article.sections.map((section, index) => <section id={`article-section-${index}`} key={`${section.heading}-${index}`}><h2 className="section-heading">{section.heading}</h2><p className="muted">{section.body}</p></section>)}<div className="secondary-dark-card"><h2>Keep the founder in the frame.</h2><p>An opportunity is only useful if the person starting it can live with the tradeoffs.</p></div></article><aside className="secondary-aside"><nav className="glass-panel secondary-aside-card secondary-toc" aria-label="In this article"><p className="secondary-meta">In this article</p>{article.sections.map((section, index) => <a href={`#article-section-${index}`} key={`${section.heading}-${index}`}>{section.heading}<ArrowDown size={14} aria-hidden="true" /></a>)}</nav><a className="glass-panel secondary-related-card" href="/browse"><span>Explore the idea library</span><ArrowUpRight size={20} aria-hidden="true" /></a></aside></div></>;
}

export function PricingPage() {
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Free means free" title="The whole library. Yours to read." description="You should be able to understand an opportunity before spending anything on it." /><div className="secondary-pricing-layout"><section className="glass-panel secondary-free-card"><div className="secondary-tool-top"><span className="secondary-icon"><Sprout size={27} aria-hidden="true" /></span><span className="pill">Always open</span></div><h2>BBI Library</h2><p className="secondary-free-word">Free<span>to read, in full</span></p><ul className="secondary-check-list">{["290 researched business-idea blueprints", "14 categories to explore", "Customers, economics, and year-one risks", "Honest founder-fit verdicts", "No signup, paywall, or email gate"].map((item) => <li key={item}><Check size={18} aria-hidden="true" />{item}</li>)}</ul><a href="/browse" className="button button-primary">Find your starting point<ArrowRight size={17} aria-hidden="true" /></a></section><div className="secondary-pricing-copy"><p className="eyebrow">An open library</p><h2>Good research should help you decide.</h2><p className="muted">Including the decision to walk away. Every founder-fit verdict is part of the blueprint.</p><div className="secondary-dark-card"><ShieldCheck size={26} aria-hidden="true" /><h3>“Do not build this one” belongs here too.</h3><p>The inconvenient parts carry the same weight as the opportunity.</p></div><a className="text-link" href="/about">Why BBI exists <ArrowUpRight size={17} aria-hidden="true" /></a></div></div><section className="secondary-section"><h2 className="section-heading">Before you browse</h2><FaqAccordion entries={libraryFaqs} /></section></div>;
}

export function AboutPage() {
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="About BBI" title="An idea is a beginning. Not a promise." description="BBI is businessidea.io: a free, human-curated library of researched business-idea blueprints." /><div className="secondary-about-feature"><div className="glass-panel secondary-seed-image"><img src="/images/home/golden-seed-business-idea-research-growth-sculpture.webp" alt="Golden seed business idea research growth sculpture for a thoughtful startup beginning" width="640" height="640" /></div><div><p className="eyebrow">Built around the founder</p><h2 className="section-heading">Clarity before commitment.</h2><p className="muted">For someone starting from zero, the useful question is not just whether a business can work. It is whether it can work for them.</p><p className="muted">That is why every blueprint finishes with a straight founder-fit verdict, including “do not build this one.”</p><a href="/browse" className="button button-primary">Explore the library<ArrowRight size={17} aria-hidden="true" /></a></div></div><section className="secondary-section"><h2 className="section-heading">The questions that guide the research</h2><div className="secondary-principle-grid">{validationPrompts.map((item) => <div className="glass-panel secondary-principle" key={item.key}><item.icon size={24} aria-hidden="true" /><h3>{item.title}</h3></div>)}</div></section><section className="glass-panel secondary-about-draft"><DraftNote>Editorial draft · The founder story and research process will be added here.</DraftNote>{/* PLACEHOLDER: founder story, editorial process, sourcing, and update policy. */}<h2 className="section-heading">The people and process behind BBI</h2><p className="muted">A space for the founder story, research process, source standards, and how the library stays useful.</p></section></div>;
}

export function ServicesPage() {
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="What BBI offers" title="A place to explore. Tools to think." description="Start with researched blueprints, compare the tradeoffs, and work through the numbers at your own pace." /><div className="secondary-service-grid"><a href="/browse" className="glass-panel secondary-service-card"><span className="secondary-icon"><BookOpen size={28} aria-hidden="true" /></span><span className="pill">Free library</span><h2>Business-idea blueprints</h2><p className="muted">Customers, economics, risks, and an honest founder-fit verdict.</p><span className="text-link">Browse the library <ArrowUpRight size={17} aria-hidden="true" /></span></a><a href="/calculator" className="glass-panel secondary-service-card"><span className="secondary-icon"><CalculatorIcon size={28} aria-hidden="true" /></span><span className="pill">Free tools</span><h2>Your numbers, worked through</h2><p className="muted">Simple calculators with visible formulas and empty inputs ready for your figures.</p><span className="text-link">Visit the workbench <ArrowUpRight size={17} aria-hidden="true" /></span></a><a href="/list" className="glass-panel secondary-service-card"><span className="secondary-icon"><Compass size={28} aria-hidden="true" /></span><span className="pill">Free collections</span><h2>A more focused starting point</h2><p className="muted">Read by category and compare blueprints that share your constraints.</p><span className="text-link">Explore collections <ArrowUpRight size={17} aria-hidden="true" /></span></a></div><div className="secondary-inline-note"><Mail size={24} aria-hidden="true" /><div><h2>For other enquiries</h2><p className="muted">Additional service information is being prepared.</p><a className="text-link" href="/contact">Visit the contact page <ArrowUpRight size={16} aria-hidden="true" /></a></div></div>{/* PLACEHOLDER: any additional approved services, scope, and enquiry details. */}</div>;
}

export function ContactPage() {
  const prefix = useId();
  const [reviewed, setReviewed] = useState(false);
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Contact" title="A useful conversation starts here." description="A place for questions about the library, research corrections, and general enquiries." /><div className="secondary-contact-layout"><form className="glass-panel secondary-form" onSubmit={(event) => { event.preventDefault(); setReviewed(true); }} onChange={() => setReviewed(false)}><h2>Your message</h2><p className="secondary-draft"><Mail size={16} aria-hidden="true" />Contact form preview · Sending is not connected.</p><div className="secondary-fields"><div className="secondary-field"><label className="field-label" htmlFor={`${prefix}-name`}>Your name</label><input className="input" id={`${prefix}-name`} name="name" autoComplete="name" required /></div><div className="secondary-field"><label className="field-label" htmlFor={`${prefix}-email`}>Email address</label><input className="input" id={`${prefix}-email`} name="email" type="email" autoComplete="email" required /></div></div><div className="secondary-field"><label className="field-label" htmlFor={`${prefix}-topic`}>What is it about?</label><select className="input" id={`${prefix}-topic`} name="topic"><option>General enquiry</option><option>Research correction</option><option>Library feedback</option></select></div><div className="secondary-field"><label className="field-label" htmlFor={`${prefix}-message`}>Your message</label><textarea className="input" id={`${prefix}-message`} name="message" rows={6} required /></div><button className="button button-primary" type="submit">Check message<ArrowRight size={17} aria-hidden="true" /></button>{reviewed && <p role="status" className="secondary-form-status"><CheckCheck size={19} aria-hidden="true" />Your fields are complete. Your message has not been sent or saved; sending is not connected.</p>}</form><aside className="secondary-aside"><div className="secondary-dark-card"><CircleHelp size={28} aria-hidden="true" /><h2>Looking for an answer?</h2><p>The questions page covers how the library works.</p><a href="/faq" className="button button-secondary">Browse questions<ArrowUpRight size={16} aria-hidden="true" /></a></div><div className="glass-panel secondary-aside-card"><p className="secondary-meta">Contact details</p>{/* PLACEHOLDER: approved contact address and response information. */}<p className="muted">Direct contact details will be added here.</p><DraftNote>Contact details pending</DraftNote></div></aside></div></div>;
}

export function SignInPage() {
  return <div className="bbi-page secondary-page"><div className="secondary-account-layout"><section className="secondary-account-message"><p className="eyebrow">The door is open</p><h1 className="page-heading">You can start right here.</h1><p className="secondary-lead muted">The entire BBI library is free. No account, password, or email address stands between you and a blueprint.</p><a href="/browse" className="button button-primary">Explore the library<ArrowRight size={17} aria-hidden="true" /></a></section><section className="glass-panel secondary-account-card"><span className="secondary-icon"><LockKeyhole size={29} aria-hidden="true" /></span><h2>Account access</h2><p className="muted">This area is reserved for future account access. Sign-in is not connected in this preview.</p><DraftNote>Account preview · No credentials collected</DraftNote><div className="secondary-account-field"><span>Email address</span><span className="secondary-account-line" /></div><div className="secondary-account-field"><span>Password</span><span className="secondary-account-line" /></div><button type="button" className="button button-secondary" disabled>Sign-in unavailable</button><p className="secondary-field-help">An account is never required to read the library.</p></section></div></div>;
}

export type LegalPageKey = "privacy" | "terms" | "disclaimer" | "gdpr" | "refund-policy";
type LegalContent = { title: string; description: string; sections: { heading: string; body: string }[] };
// PLACEHOLDER: all legal wording below is a clearly labelled draft slot, not an operative policy.
const legalContent: Record<LegalPageKey, LegalContent> = {
  privacy: { title: "Privacy policy", description: "How personal information is handled, explained in one place.", sections: [ { heading: "Information and purpose", body: "The approved description of information collected, its purpose, and how it is used will appear here." }, { heading: "Storage and sharing", body: "The approved retention periods, service providers, and sharing practices will appear here." }, { heading: "Your choices", body: "The approved process for privacy requests and contact details will appear here." } ] },
  terms: { title: "Terms of use", description: "The terms that will govern use of the BBI website and its content.", sections: [ { heading: "Using the library", body: "Approved terms for website access and permitted use will appear here." }, { heading: "Content and intellectual property", body: "Approved terms for ownership, attribution, and reuse of research will appear here." }, { heading: "Responsibilities and changes", body: "Approved provisions on responsibilities, applicable law, and changes to these terms will appear here." } ] },
  disclaimer: { title: "Disclaimer", description: "The scope and limitations of the research and tools on BBI.", sections: [ { heading: "Research and editorial content", body: "The approved statement about the nature and limitations of the research will appear here." }, { heading: "Calculators and estimates", body: "The approved statement about user inputs, calculations, and estimates will appear here." }, { heading: "Your decisions", body: "The approved statement about independent assessment and professional advice will appear here." } ] },
  gdpr: { title: "Data protection", description: "A dedicated place for data protection information and requests.", sections: [ { heading: "Data controller and legal basis", body: "Verified controller details and the applicable legal bases will appear here." }, { heading: "Data rights", body: "The approved explanation of applicable data rights and how to exercise them will appear here." }, { heading: "Requests and concerns", body: "The verified contact channel and applicable supervisory authority information will appear here." } ] },
  "refund-policy": { title: "Refund policy", description: "The BBI library is free to read, with no paywall or email gate.", sections: [ { heading: "Free library access", body: "The approved policy will explain that access to the researched library is free." }, { heading: "Any future paid services", body: "If a paid service is introduced, its approved cancellation and refund terms will appear here before it is offered." }, { heading: "Contact", body: "Verified contact details for questions about this policy will appear here." } ] },
};

export function LegalPage({ page, content }: { page: LegalPageKey; content?: LegalContent }) {
  const document = content ?? legalContent[page];
  return <div className="bbi-page secondary-page"><SecondaryHeader eyebrow="Legal" title={document.title} description={document.description} /><div className="secondary-legal-layout"><nav className="glass-panel secondary-legal-nav" aria-label="Legal pages">{Object.entries(legalContent).map(([key, item]) => <a href={`/${key}`} key={key} aria-current={page === key ? "page" : undefined}>{item.title}<ArrowUpRight size={14} aria-hidden="true" /></a>)}</nav><article className="glass-panel secondary-legal-document">{!content && <DraftNote>Draft template · Final policy text and effective date have not been supplied.</DraftNote>}<p className="secondary-meta">{content ? "Policy document" : "Effective date pending"}</p>{document.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2><p className="muted">{section.body}</p></section>)}<a href="/contact" className="text-link">Contact BBI<ArrowUpRight size={16} aria-hidden="true" /></a></article></div></div>;
}

